pocl/pocl

- include/_kernel.h
Fixed the barrier duplication problem by using the attribute`noduplicate`.
> Fixed the barrier duplication problem

- lib/CL/pocl_llvm_api.cc
Probably left over from changing addPassesToEmitFile to
addPassesToEmitMC. Won't change behaviour as CGFT_ObjectFile is 1 and
default value of the DisableVerify argument is true.
See http://llvm.org/doxygen/classllvm_1_1TargetMachine.html#a3d780c056467479af56e78d2adb6a200.
> Don't pass an enum value as a bool.

- config.h.in.cmake
It should be 1 on a big endian target but was actually empty.
> Corrected WORDS_BIGENDIAN for cmake build.

- lib/CL/devices/basic/basic.c
- lib/CL/devices/cellspu/cellspu.c
- lib/CL/devices/pthread/pthread.c
- lib/CL/devices/tce/ttasim/ttasim.cc
CL_DEVICE_MAX_WORK_ITEM_SIZES is an array describing the maximum
number of work-items that can be indexed in a given dimension in a
work-group (not globally), so it doesn't make any sense for it to be
larger than CL_DEVICE_MAX_WORK_GROUP_SIZE, which is the overall limit
in the number of work-items in a work-group.
Just as well, since we don't have hardware work-item indices (which is
the case on GPUs instead) it also doesn't make any sense for any of the
values to be _less_ than the maximum work-group size (i.e. there's no
reason to not allow 1×1×MAX as well as MAX×1×1 and 1×MAX×1), so just
set each element of max_work_item_sizes to the value of
max_work_group_size.
Signed-off-by: Giuseppe Bilotta <giuseppe.bilotta@gmail.com>
> Clip max_work_item_sizes to max_work_group_size

- lib/CL/devices/basic/basic.c
- lib/CL/devices/cellspu/cellspu.c
- lib/CL/devices/pthread/pthread.c
- lib/CL/devices/tce/tce_common.cc
- lib/CL/pocl_llvm_api.cc
- lib/llvmopencl/Workgroup.cc
- scripts/pocl-kernel.in
- tests/runtime/Makefile.am
- tests/runtime/test_clBuildProgram.c
- tests/runtime/test_link_error.c
- tests/testsuite-runtime.at
While testing some simple programs in a course I'm running I discovered an interesting issue with pocl: if a kernel called 'init' is present, the program will fail to launch due to a link error in the device code. However, the link error doesn't actually happen when building the program, but when kernels are actually invoked.
This patch series thereby tests for two issues:
1. a spec violation, by which link failures are not reported from within clBuildProgram(), even though they should (instead, they are reported further on when the kernels are actually linked at launch time);
2. the actual 'init' bug, which is caused by the kernel launcher name mangling prepending a '_' to the kernel name, causing the '_init' symbol to be double-defined;
The last patch actually fixes the second bug, by …
> Link failures

- CHANGES
- include/_kernel_c.h
- lib/kernel/CMakeLists.txt
- lib/kernel/get_image_dim.cl
- lib/kernel/sources.mk
- tests/kernel/image_query_funcs.c
- tests/kernel/test_image_query_funcs.cl
This implements get_image_dim for 2D images and arrays, and for 3D images.
This should fix issue #55.
(Note that the issue also mentions some write image functions in a later comment. This is not addressed here.)
> Implement get_image_dim

- tests/runtime/Makefile.am
- tests/runtime/test_event_cycle.c
- tests/runtime/test_read-copy-write-buffer.c
- tests/testsuite-runtime.at
This patchset adds two small tests:
* the first is a simple test for reading, copying and writing buffers (nothing special, passes as-is);
* the second is a test for the “neverending loop” that was fixed by the (merged) pull requesnt #172 (I tested it without those patches and it fails as expected, after a 30s timeout, it passes with the latest master).
> Two more tests

- include/_kernel_c.h
- lib/llvmopencl/GenerateHeader.cc
- lib/llvmopencl/LLVMUtils.h
This is a (tentative) fix to restore image support in LLVM 3.2 which I broke in the `get_image_dim()` implementation. I don't have LLVM 3.2 around, so I can't test if it actually does, but at least it doesn't break anything in later versions.
> Image fix for llvm32

- lib/CL/devices/basic/basic.c
- lib/CL/devices/pthread/pthread.c
- lib/CL/devices/topology/pocl_topology.c
- lib/CL/devices/topology/pocl_topology.h
This patch series adjusts a number of (arbitrary, on CPU) limits to things such as image and buffer sizes. It also fixes the base address align value which should be in bits, not bytes.
> Improve device limits

- lib/CL/clEnqueueFillImage.c
- lib/CL/clEnqueueMapBuffer.c
- lib/CL/clEnqueueMapImage.c
- lib/CL/clEnqueueMarkerWithWaitList.c
- lib/CL/clEnqueueReadImage.c
- lib/CL/clEnqueueUnmapMemObject.c
- lib/CL/clEnqueueWriteImage.c
- lib/CL/pocl_llvm_api.cc
- lib/llvmopencl/ParallelRegion.cc
- lib/llvmopencl/ParallelRegion.h
- tests/runtime/CMakeLists.txt
- tests/runtime/Makefile.am
- tests/runtime/test_event_cycle.c
- tests/runtime/test_event_free.c
- tests/runtime/test_read-copy-write-buffer.c
- tests/testsuite-runtime.at
This is a second round of fixes that are determined by more-or-less static analysis (where 'static' refers to my own eyes this time). I got interested in this round of fixes when I noticed a double-free when I happened to use an invalid event in a waitlist, so I went through all the clEnqueue* that seemed to be affected by similar issues, wrote tests triggering the relevant errors (mostly segmentation faults) and fixed those that I found.
> Memory access violation fixes

- lib/CL/clCreateContextFromType.c
- lib/CL/clCreateUserEvent.c
- lib/CL/clEnqueueCopyBufferRect.c
- lib/CL/clEnqueueCopyBufferToImage.c
- lib/CL/clEnqueueMapImage.c
- lib/CL/clEnqueueNativeKernel.c
- lib/CL/clEnqueueReadBufferRect.c
- lib/CL/clEnqueueWriteBufferRect.c
- lib/CL/clFinish.c
- lib/CL/clGetEventInfo.c
- lib/CL/clReleaseEvent.c
- lib/CL/clSetUserEventStatus.c
- lib/CL/pocl_cl.h
- lib/CL/pocl_hash.c
- lib/CL/pocl_util.c
- lib/CL/pocl_util.h
- tests/kernel/image_query_funcs.c
- tests/kernel/sampler_address_clamp.c
- tests/regression/test_barrier_before_return.cpp
- tests/regression/test_barrier_between_for_loops.cpp
- tests/regression/test_early_return.cpp
- tests/regression/test_for_with_var_iteration_count.cpp
- tests/regression/test_id_dependent_computation.cpp
- tests/regression/test_loop_phi_replication.cpp
- tests/regression/test_multi_level_loops_with_barriers.cpp
- tests/regression/test_null_arg.cpp
- tests/regression/test_undominated_variable.cpp
- tests/runtime/test_clCreateKernel.c
- tests/runtime/test_event_free.c
Again, most are trivial issues detected by clang's scan-build. The only major changes are those pertaining to the general aspects of event handling, and specifically:
* the command queue is always taken from the event itself when updating its status, and it is checked for existance (since user events can have a NULL queue);
* user event handling is much closer to what is required by the specification (the only thing missing is terminating all commands that depend on a user event whose status is updated to a negative value indicating error —I'm thinking this should need a more general solution, but first I want to study the spec better to see what happens when to standard enqueued commands when any of their preceding commands fail.
> Another round of static fixes

- include/pocl_cache.h
- lib/CL/clCreateProgramWithSource.c
- lib/CL/clGetProgramBuildInfo.c
- lib/CL/clReleaseProgram.c
- lib/CL/pocl_cache.c
- lib/CL/pocl_llvm.h
- lib/CL/pocl_llvm_api.cc
- lib/llvmopencl/LLVMFileUtils.cc
- tests/runtime/test_clBuildProgram.c
This patchset should significantly improve error handling during early program builds (e.g. during preprocessing), avoid segmentation faults and properly reporting errors.
> Preprocess errors resiliency

- include/CL/cl_platform.h
- lib/CL/Makefile.am
- lib/CL/devices/pthread/pthread.c
- lib/CL/pocl_cache.c
- lib/CL/pocl_queue_util.c
- lib/llvmopencl/LLVMFileUtils.cc
- tests/runtime/test_event_cycle.c
- tests/runtime/test_read-copy-write-buffer.c
This branch contains various small corrections to make pocl build on OS X, and to avoid compiler warnings.
> Various corrections to build on OS X

- lib/CL/pocl_util.c
I had actually undone the change, but then not amended the commit. Sorry.
> Restore (void*)-to-uintptr_t cast, committed by mistake

- lib/kernel/vecmathlib-pocl/generate-files.py
- lib/kernel/vecmathlib-pocl/kernel-vecmathlib.h
This should not lead to any user-visible changes since `kernel-vecmathlib.h` is not used anywhere yet.
In principle, this file could be included from `_kernel.h` instead of most of the #define-based declarations.
> Protect half and double versions with the respective #ifdefs in kernel-vecmathlib.h

- cmake/LLVM.cmake
I suspect the check is currently wrong. It seems to be checking whether C
allows half precision types in arguments and returns. On Mips, this is not
currently allowed. However, I suspect OpenCL allows this regardless of
target. Regardless of the truth of the matter, we should be able to forcefully
enable half precision types in pocl.
This patch removes the unconventional caching mechanism for
CL_DISABLE_HALF in favour of cmake's usual method which allows the user
to specify it with -DCL_DISABLE_HALF=ON/OFF.
> [cmake] Make it possible to override CL_DISABLE_HALF.

- lib/CL/clBuildProgram.c
https://www.khronos.org/registry/cl/sdk/1.0/docs/man/xhtml/clBuildProgram.html
Khronos specification allows the option "-Werror" to be use in the clBuildProgram function.
> Option -Werror added for clBuildProgram

- lib/llvmopencl/Workgroup.cc
The first argument is the pointee type rather than the pointer type.
This fixes examples/example1 (and possibly others) on a MIPS32 target.
> Correct usage of CreateConstGEP2_32().

- doc/sphinx/source/development.rst
- tools/scripts/devel-envs.sh
CMake builds don't have a .libs directory. This change adds an optional
'cmake' argument that causes the script to work for cmake builds.
> Fix devel-envs.sh for cmake.

- CMakeLists.txt
This should partially fix the timeouts seen on the mipsel-32r2-cmake
builder since ninja will stop buffering the ctest output.
> [cmake] When cmake supports it, use USES_TERMINAL on the check target.

- tests/regression/test_issue_231.cpp
A regression test added recently uses the old `cl.hpp` header, which requires OpenGL headers. This is just a minor update to use `cl2.hpp` instead, which matches the other C++ tests and removes the OpenGL dependency.
> Update test to use cl2.hpp

- lib/llvmopencl/LLVMUtils.h
This should fix the test failures listed in #181. The issue was that image and sampler arguments were not being correctly detected (they were being mislabeled as regular pointer arguments).
> Fix checks for images/samplers when parsing kernel metadata.

- lib/kernel/CMakeLists.txt
- lib/kernel/sources-vml.mk
This was causing any use of `native_sqrt` inside a kernel to produce a linker error.
> Add native_sqrt to math builtin list

- lib/CL/pocl_llvm_api.cc
The MIPS LLVM backend is not able to detect the host and returns 'generic'
this hasn't been a problem upstream but POCL feeds this value into the
-target-cpu option which rejects it. This causes almost all tests to fail.
> [mips] Avoid getHostCPUName(), 'generic' is not a valid -target-cpu value.

- lib/CL/clCreateBuffer.c
This was causing crashes when multiple devices were being used.
> Use correct index for initialising device pointer structures

- lib/kernel/vstore.cl
This extra 't' caused me a surprisingly large amount of debugging time...
> Fix typo preventing generation of vstore double in private memory

- lib/llvmopencl/TargetAddressSpaces.cc
This should address issue #336 that I recently raised. The fix is to use the external `currentPoclDevice` handle that is also used by the Workgroup pass, and get the device target triple from this, instead of using the module's target triple.
This fixes SPIR consumption for a private backend that I'm working on and still works for x86, but I haven't been able to test any of the other non-flat address space targets such as TCE/HSA, so maybe worth a check on those platforms before merging.
> Use device triple instead of module triple for address space remapping

- doc/sphinx/source/install.rst
This brings pocl up-to-date with LLVM trunk.
Most of the changes are relatively minor. The only two that I was a little unsure of are aa7534c and 8ef244b.
I tested with LLVM 3.8 on Linux and there were no regressions in the internal test-suite.
There was one test failure with LLVM trunk, which is `test_clGetKernelArgInfo`. The issue is that the definitions for `write_imagef` in `_kernel_c.h` don't include the `write_only` flag. I'm not sure how to resolve this - can the image function declarations be moved out of this C compatible header so that we can add the appropriate qualifiers?
> Update for LLVM trunk

- lib/CL/devices/basic/basic.c
- lib/CL/devices/common.c
- lib/CL/devices/prototypes.inc
- lib/CL/pocl_cl.h
This is required for any devices that don't have unified memory with the host CPU and therefore need to manually update device memory during an unmap operation.
> Pass offset to driver unmapping routines

- lib/CL/clCreateSubBuffer.c
Missed this from my recent addition of `clSetMemObjectDestructorCallback`, otherwise any use of `clCreateSubBuffer` is likely to cause crashes.
Sorry!
> Ensure destructor callback list initialized to NULL for sub-buffers

- include/pocl.h
- lib/CL/clEnqueueCopyBufferRect.c
- lib/CL/clEnqueueCopyImage.c
- lib/CL/devices/common.c
- lib/CL/pocl_img_buf_cpy.c
- lib/CL/pocl_shared.h
- tests/runtime/test_read-copy-write-buffer.c
This should fix #349 and bring the buffer rect and image copies in line with the rest of the enqueued ops.
> Rect fixes

- lib/CL/clEnqueueCopyBufferToImage.c
- lib/CL/clEnqueueCopyImageToBuffer.c
- lib/CL/devices/basic/basic.c
- lib/CL/devices/common.c
- lib/CL/pocl_img_buf_cpy.c
- tests/runtime/CMakeLists.txt
- tests/runtime/Makefile.am
- tests/runtime/test_buffer-image-copy.c
(Re)implement buffer <-> image copies via the existing 2D (and 3D) copy mechanism. This completes the missing parts of the implementation and brings everything in line with the new command/event mechanism.
The last commit fixes a buffer fill bug which was also exposed by the buffer image copy test.
> Buffer image copy

- CREDITS
- lib/CL/pocl_timing.c
Falls back to CLOCK_MONOTONIC for Linux distributions that come without CLOCK_MONOTONIC_RAW, e.g. SLES (used in Cray's software environment).
- Including "linux/time.h" instead of "time.h" would also solve the issue, but conflicts with other "time.h" includes across the project, which would lead to a much larger patch, so keeping it simple.
- The generic fall back to CLOCK_REALTIME would also work, but CLOCK_MONOTONIC is closer to CLOCK_MONOTONIC_RAW, see http://man7.org/linux/man-pages/man2/clock_gettime.2.html
- Also changed the "#warn" to "#warning", as gcc 5.3.0 wouldn't accept "#warn" and yield an error
> Fixed lib/CL/pocl_timing.c

- CHANGES
- CMakeLists.txt
- ToolchainExample.cmake
- cmake/FindHwloc.cmake
- doc/sphinx/source/pocl_binary.rst
- lib/CL/devices/CMakeLists.txt
- lib/CL/devices/topology/CMakeLists.txt
Note this is only for LLVM-less builds.
Toolchain.example has the required steps to use it.
> Crosscompilation support

- CMakeLists.txt
- cmake/LLVM.cmake
- examples/CMakeLists.txt
- include/pocl_cache.h
- lib/CL/clBuildProgram.c
- lib/CL/clCreateKernel.c
- lib/CL/clEnqueueNDRangeKernel.c
- lib/CL/pocl_cache.c
- lib/CL/pocl_llvm.h
- lib/CL/pocl_llvm_api.cc
1) fix some random annoying warnings from CMake,
2) remove a redundant (for HSA at least) mkdir in clEnqueueNDRangeKernel() - improves performance of small kernel enqueues
> Random fixes

- examples/example1-spir32/example1_exec.c
- examples/example1-spir64/example1_exec.c
- lib/CL/clBuildProgram.c
The [`cl_khr_spir` extension](https://www.khronos.org/registry/cl/sdk/2.0/docs/man/xhtml/cl_khr_spir.html) requires any application that makes use of SPIR to pass the `-x spir` and `-spir-std=*` flags to `clBuildProgram`. This patch adds support for these flags so that pocl can work with a SPIR-based application (for context I'm currently working with the [ComputeCpp implementation of SYCL from Codeplay](https://www.codeplay.com/products/computesuite/computecpp)).
> Add support for SPIR build flags

- lib/CL/devices/common.c
Memfill commands pattern argument allocated as aligned. Matching aligned free added.
> Pattern field of memfill command allocated as aligned. Matching free added as aligned free.

- examples/CloverLeaf/CMakeLists.txt
- examples/VexCL/CMakeLists.txt
- examples/clBLAS/CMakeLists.txt
- examples/clFFT/CMakeLists.txt
- examples/piglit/CMakeLists.txt
For the most part, just add a check that a ICD loader is available.
This should make the ARM buildbot pass again.
> Add dependency checks for example-tests

- lib/CL/clBuildProgram.c
- tests/runtime/test_clBuildProgram.c
clBuildProgram compile options which supported by LLVM 3.9 added.
Also telated test cases for new and existing compile options added.
> clBuildProgram compile options added

- lib/CL/clCreateImage.c
Free added for the resource allocated for checking supported image formats.
> Fixed leak in clCreateImage

- include/pocl.h
- lib/CL/clBuildProgram.c
- lib/CL/clCreateProgramWithBinary.c
- lib/CL/clCreateProgramWithSource.c
- lib/CL/clReleaseProgram.c
- lib/CL/pocl_cl.h
- tests/runtime/test_clBuildProgram.c
pfn_notify callback added for clBuildProgram, and related test added to clBuildProgram tests.
OCL1.2 spec says:
"If pfn_notify is not NULL, clBuildProgram does not need to wait for the build to complete and can return immediately once the build operation can begin."
This feature still missing.
Also -Werror test revised to test full functionality: warning in the kernel build turned to error and checked in the test.
> pfn_notify callback added for clBuildPorgram, related test added and -Werror test revised

- include/pocl.h
- lib/CL/clBuildProgram.c
- lib/CL/clCreateProgramWithBinary.c
- lib/CL/clCreateProgramWithSource.c
- lib/CL/clGetProgramBuildInfo.c
- lib/CL/pocl_cl.h
- tests/runtime/test_clBuildProgram.c
- tests/runtime/test_clCreateProgramWithBinary.c
Based on OCL1.2 spec
if program will be compiled using clCompileProgram its binary_type will be set to CL_PROGRAM_BINARY_TYPE_COMPILED_OBJECT.
clCompileProgram is currently missing in pocl!
if program was created by clLinkProgram which is called with the –createlibrary link option its binary_type will be set to CL_PROGRAM_BINARY_TYPE_LIBRARY.
clLinkProgram is currently missing in pocl!
clCreateProgramWithBinary
sets CL_PROGRAM_BINARY_TYPE_EXECUTABLE
clCreateProgramWithSource
sets CL_PROGRAM_BINARY_TYPE_NONE
> clGetProgramBuildInfo binary_type information added

- lib/CL/pocl_binary.c
When a processor does not support unaligned access, reading a pocl binary file creates an unauthorized memory access.
"memcpy" function is normaly implemented so that it does no unaligned access if the architecture does not support it.
> use memcpy to avoid unaligned access in pocl_binary

- lib/kernel/read_image.cl
out_of_bound check during read_imagef also does clamping.
However as coords passed by value it was effectless.
Coords passed by reference so clamped values updated.
> read_imagef clamp bug fix

- include/_kernel_c.h
- lib/kernel/read_image.cl
added missing read_imagef functions with image2d_array_t and
no sampler versions.
Pocl currently does not support float coords so read_imagef
with float coord arguments commented out.
> adding read_imagef missing functions

- examples/piglit/CMakeLists.txt
The piglet tests require `ocd-icd`, otherwise they just use whatever OpenCL platform is first on the host system.
Also use an empty string for the INSTALL_COMMAND instead of `/bin/true`, since the latter isn't available on all *nix systems.
> Fix piglit examples

- CMakeLists.txt
- cmake/spir-cc-test-kernel.cl
Here's a snippet of CMake that makes the patch from #1 detectable both for other CMake code and for user code through the device version number.
Full disclosure: I learned what little CMake I needed for this roughly a half hour ago. If there is a better way to do this, let me know.
> Detect presence of SPIR CC patch, make visible in version number

- lib/CL/devices/common.c
Looks like this was just missing a mutex around the deletion of the mapping.
Fixes issue #447.
Candidate for cherry-picking to 0.14? Without this I don't always get a full suite of passes.
> Fix race condition when unmapping memory objects

- lib/CL/clCreateCommandQueueWithProperties.c
This fixes the creation of command queues with OpenCL >= 2.0, so long as the CL_QUEUE_PROPERTIES property is set.
Please let me know if you'd prefer to have this pull request created against the release_0_14 branch.
> Correctly create command queue

- lib/CL/pocl_binary.c
cherrypicked a single fix for 0.14
> Fix #449: Miscounts arguments upon loading kernel from binary

- CHANGES
- lib/CL/clEnqueueNDRangeKernel.c
- tests/regression/test_issue_445.cpp
This is a set of cleanups and fixes for `clEnqueueNDRangeKernel`. The main highlights are checks that for kernels with a required work-group size the user submitted that work-group size (which should fix #450), and a rewrite of the logic used to determine the work-group size in the NULL case, designed around the hard sizing constrains of dividing the global size, being less than the maximum allowed local size in each dimension while still trying to take the preferred work-group size multiple of the device into account.
> NDRange fixes

- lib/CL/pocl_llvm_api.cc
- lib/llvmopencl/AutomaticLocals.cc
- tests/regression/CMakeLists.txt
- tests/regression/test_autolocals_in_constexprs.cpp
Replacing an automatic local with an argument doesn't work if one of the
users is a constant expressions, since function arguments aren't
constants. Instead, we first replace any constant expression users with
their equivalent instructions.
Fixes #467.
> Fix AutomaticLocals breaking constant expressions

- lib/CL/clCreateContext.c
- lib/CL/clCreateContextFromType.c
- lib/CL/clGetDeviceIDs.c
- lib/CL/devices/basic/basic.c
- lib/CL/devices/cuda/pocl-cuda.c
- lib/CL/devices/cuda/pocl-ptx-gen.cc
- lib/CL/devices/devices.c
- lib/CL/devices/devices.h
- lib/CL/devices/hsa/pocl-hsa.c
- lib/CL/devices/prototypes.inc
- lib/CL/devices/pthread/pthread.c
- lib/CL/devices/tce/ttasim/ttasim.cc
- lib/CL/devices/topology/pocl_topology.c
- lib/CL/devices/topology/pocl_topology.h
- lib/CL/pocl_cl.h
I dislike it when platforms `abort()` on error, since this prevents the invoking application from properly handling error conditions. This is particularly damning on initialization, which is actually one of the easiest situations to handle (for example by changing platform).
This patch series proposes a method to handle error condition during initialization (essentially, marking problematic devices as unavailable instead of simply killing everything). It is not complete, since I'm not particularly familiar with the TCE and HSA code and I'm not in the condition to test things.
> [RFC] Cleanup init devices

- cmake/LLVM.cmake
LLVM's CPU detection is very basic, it parses /proc/cpuinfo and uses
information from their to look up CPUs in its own internal tables.
These tables are incomplete, so it's not uncommon for LLVM to not
be able to detect the CPU.
Ideally pocl would use something better than llc --version for CPU
detection, but for now we can at least fallback to the generic
cpu when LLVM can't detect the host.
> Use generic cpu when LLVM can't detect the host processor

- doc/sphinx/source/cuda.rst
- lib/CL/clCreateCommandQueue.c
- lib/CL/clReleaseCommandQueue.c
- lib/CL/clSetUserEventStatus.c
- lib/CL/clWaitForEvents.c
- lib/CL/devices/basic/basic.c
- lib/CL/devices/common.c
- lib/CL/devices/cuda/pocl-cuda.c
- lib/CL/devices/cuda/pocl-ptx-gen.cc
- lib/CL/devices/hsa/pocl-hsa.c
- lib/CL/devices/prototypes.inc
- lib/CL/devices/pthread/pthread.c
- lib/CL/devices/tce/tce_common.cc
- lib/CL/pocl_cl.h
- lib/CL/pocl_util.c
This patch makes the CUDA backend deal with command submission asynchronously. This enables commands to be overlapped when using multiple devices, or with multiple command queues targeting the same device (e.g. overlapping compute with data transfers). Event dependencies are now handled using CUDA events instead of blocking on the host.
The `events` category of the Khronos OpenCL conformance test suite now passes for the CUDA backend. I've also added a small section to the CUDA docs that list all the conformance test categories that pass.
There's a small handful of changes and bug fixes outside of the CUDA backend, but I don't think there's anything controversial.
> [CUDA] Asynchronous command submission

- lib/CL/clBuildProgram.c
- lib/CL/clReleaseProgram.c
`program->compiler_options` is set to `modded_options` in `clBuildProgram`, when `modded_options` is result of a sequence of calloc and realloc in the `APPEND_TOKEN` macro.
> Field program->compiler_options is not free-ed in clReleaseProgram

- lib/CL/clCreateBuffer.c
When we create a buffer on a multi-devices platform, we do not want
any clRetainMemObject on it so that only one clReleaseMemObject is
needed to free the buffer.
> fix issue #486 (Release MemObject on multi-devices platform)

- cmake/LLVM.cmake
CLANG_RESOURCE_DIR did not account for LLVM_LIBDIR_SUFFIX.
LLVM_LIBDIR is derived from llvm-config which takes care of this.
> [CMake] Use LLVM_LIBDIR to construct CLANG_RESOURCE_DIR

- lib/CL/clCreateKernel.c
- lib/CL/pocl_binary.c
We need to skip program.bc in a pocl_binaries when we want to have
information on kernels from the start of a pocl_binaries.
When running POCL offline, we do not need to take care of
program->binaries (even if they are present) as we do not have a
compiler available.
> fix issue #537 (pocl_binaries are not functionnal)

- lib/kernel/vload_store_half_f16c.c
This way we don't need to include x86intrin.h which redefines the size_t
typedef which is also defined in pocl_types.h
This fixes the build on i686:
In file included from /builddir/build/BUILD/pocl-53ef5e89aa99b5e85ad512ff46aa8f38b36acf4f/lib/kernel/vload_store_half_f16c.c:50:
In file included from /usr/lib/clang/5.0.0/include/x86intrin.h:29:
In file included from /usr/lib/clang/5.0.0/include/immintrin.h:32:
In file included from /usr/lib/clang/5.0.0/include/xmmintrin.h:39:
In file included from /usr/lib/clang/5.0.0/include/mm_malloc.h:27:
In file included from /usr/include/stdlib.h:31:
/usr/lib/clang/5.0.0/include/stddef.h:62:23: error: typedef redefinition with different types ('unsigned int' vs 'ulong' (aka 'unsigned long'))
typedef __SIZE_TYPE__ size_t;
^ …
> Use the clang builtin names for intrinsics in vload_store_half_f16c.c

- lib/CL/clCreateUserEvent.c
- lib/CL/clReleaseEvent.c
- lib/CL/clSetUserEventStatus.c
- lib/CL/clWaitForEvents.c
- lib/CL/devices/basic/basic.c
- lib/CL/devices/common.c
- lib/CL/devices/cuda/pocl-cuda.c
- lib/CL/devices/hsa/pocl-hsa.c
- lib/CL/devices/pthread/pthread.c
- lib/CL/devices/tce/tce_common.cc
- lib/CL/pocl_cl.h
- lib/CL/pocl_util.c
Already described at pocl-devel, so only shortly:
This PR attempts to fix the remaining issues with user events.
In particular, pocl_broadcast() now calls notify on events also in
CL_QUEUED state, and also calls notify on events which depend on failed
*user* events. Some problems remain:
1) i've updated all drivers except CUDA which seems to have its own way
of handling events.
2) after any event fails, the state is "implementation defined". Code in this PR just sets all dependent events to failed.
> User events handling

- doc/sphinx/source/cuda.rst
- lib/CL/devices/cuda/pocl-ptx-gen.cc
Make module verifiation opt-in, since the pocl linker currently
generates invalid metadata.
This is a workaround for #525, to make the CUDA backend work with LLVM 5+.
> [CUDA] Add POCL_CUDA_VERIFY_MODULE environment variable

- examples/EinsteinToolkit/EinsteinToolkit.c
- lib/CL/clCreateSubDevices.c
Migrated from #554 -- note, the segfault went away after a clean rebuild.  Instead I just had a failing test.
---
The relevant part of the spec is:
>CL_INVALID_VALUE if out_devices is not NULL and **num_devices is less than the number of sub-devices** created by the partition scheme.
instead, it was checking for exact equality (`clCreateSubDevices.c::126`).
On my 40 core server, this manifested as an error in the `EinsteinToolkit_subDev` test, as it would split `40 / 2 -> 20 != 2` passed in `clCreateSubDevices (main_device_id, props, 2, subdevs, &retval);`
Instead that should be the size of the full sub device array (128).
> Fix num devices check

- doc/sphinx/source/env_variables.rst
Should be XDG_CACHE_HOME, not XDG_CACHE_DIR.
> Documentation: Fix a typo in an environment variable name.

- tests/kernel/CMakeLists.txt
The test shuffle_* tests pass on arm64 but fail the build as they are
expected to fail. Fix this by dropping the hunk marking the tests as
failing.
Fixes #610
> tests/kernel: test_shuffle_* pass on arm64

- lib/CL/clGetDeviceInfo.c
Introduce a variant of POCL_RETURN_DEVICE_INFO_WITH_IMPL_CHECK that
only complains for null values if support for a specific extension is
claimed, and use it when returning the default and native vector widths
for the half type when cl_khr_fp16 is not supported.
Signed-off-by: Giuseppe Bilotta <giuseppe.bilotta@gmail.com>
> Extension-pased device info check

- cmake/LLVM.cmake
- config.h.in.cmake
- include/_kernel_c.h
- include/pocl.h
- lib/CL/pocl_llvm_build.cc
- lib/CL/pocl_llvm_utils.cc
- lib/llvmopencl/BarrierTailReplication.cc
- lib/llvmopencl/LLVMFileUtils.cc
This is a development branch to have PoCL working with ToT Clang/LLVM.
It is not intended to be merged for now but mostly to have an `llvm-7.0` branch Khronos and others can work with and contribute, towards the great unification around ToT OpenCL/SPIR/SPIR-V/SYCL...
On my laptop the `ctest -j1`seems good:
```
99% tests passed, 1 tests failed out of 121
Label Time Summary:
EinsteinToolkit    =   5.42 sec (2 tests)
cuda               =   3.94 sec (49 tests)
hsa                =   0.22 sec (3 tests)
internal           =  15.46 sec (107 tests)
kernel             =   2.65 sec (29 tests)
regression         =   2.42 sec (35 tests)
runtime            =   8.71 sec (21 tests)
spir               =   0.48 sec (1 test)
tce                =   0.56 sec (8 tests)
workgroup          =   1.45 sec (19 …
```
> [WIP] Clang/LLVM 7.0 ToT

- lib/kernel/cuda/CMakeLists.txt
When building the cuda driver with LLVM 7, compilation of the device
functions may fail with the error:
/usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
Adding `-ffreestanding` to the compilation flags for the cuda driver
avoids attempts to access the host include files.
Fixes #671.
> CUDA device code is not hosted

- lib/CL/devices/pthread/pthread.c
pocl_pthread_update_event() notifies event waiters about changes of status. It should use pthread_cond_broadcast() rather than pthread_cond_signal() so all waiters get notified in case multiple threads are waiting on the event.
> pthread: broadcast event updates with pthread_cond_broadcast()

- lib/CL/devices/common.c
- lib/CL/pocl_cl.h
- lib/poclu/cl_half.c
With this change I can build on a CentOS 5 machine (Needed to build a wheel for pyopencl).
Fixes https://github.com/pocl/pocl/issues/678
> Support older GLIBC

- CMakeLists.txt
Currently only installing or auto detection of OpenCL headers is possible. 
With this patch it is possible to install (cmake -DINSTALL_OPENCL_HEADERS=1/YES), not install (cmake -DINSTALL_OPENCL_HEADERS=0/NO) or auto detect (cmake). 
With no option set, it behaves like before.
> Add option to disable installing of OpenCL headers

- include/pocl.h
- lib/CL/devices/basic/basic.c
- lib/CL/devices/hsa/pocl-hsa.c
- lib/CL/devices/pthread/pthread.c
- lib/CL/devices/pthread/pthread_utils.c
- lib/CL/devices/tce/ttasim/ttasim.cc
- lib/CL/pocl_cl.h
- lib/llvmopencl/AutomaticLocals.cc
- lib/llvmopencl/LLVMUtils.cc
- lib/llvmopencl/LLVMUtils.h
- lib/llvmopencl/Workgroup.cc
- tools/scripts/format-branch.sh
- tools/scripts/format-last-commit.sh
Allows devices to set "device_alloca_locals" to 1, which causes then Workgroup.cc to generate code that allocates local memory from stack (using the alloca LLVM IR instruction) instead of expecting it to be preallocated by the host launcher. In that case the hidden local args contain the size of the local buffer to allocate instead of the buffer pointer.
> Device-side allocation of local memory to stack

- doc/sphinx/source/accel.rst
Clarify the intended use of the example RTL, as well as note the possibility of `sudo` affecting environment variables.
> Update accel documentation

- lib/CL/pocl_util.c
So i believe this is a small bug, I could be wrong though I think negating region[0] by 1 was always yielding a byte size 1 byte smaller than intended. For example a 2D region where we wish to specify a buffer of 1600 bytes would yield 1599 (sorry for the bad pseudo-code):
```
int origin[3] = {0, 0, 0}
int region[3] = {80, 20, 1}; // z always has to be 1 for spec conformance
int rp = region[0]; // 80
int sp = region[1] * rp; // 20 * 80 = 1600 
```
Old formula:
`origin[0] + region[0]-1 + rp * (origin[1] + region[1]-1) + sp * (origin[2] + region[2]-1);`
**0 + 80 - 1 + 80 * (0 + 20 - 1) + 1600 * (0 + 1 - 1) = 1599**
Updated formula:
`origin[0] + region[0] + rp * (origin[1] + region[1]-1) + sp * (origin[2] + region[2]-1);`
**0 + 80 + 80 * (0 + 20 - 1) + 1600 * (0 + 1 - 1) = 1600**
I think the …
> pocl_buffer_boundcheck_3d off by 1

- lib/CL/pocl_llvm_build.cc
When the resources dir is determined at compile time, it also includes
the full version (e.g. /usr/lib64/clang/8.0.0/include/opencl-c.h). If
clang gets a minor version update later (e.g. from 8.0.0 to 8.0.1), pocl
will still add the obsolete path for the header lookup.
Determine the path at runtime instead. LLVM 9.0 adds a static method
llvm::driver::Driver::GetResourcesPath(...) which can be used, LLVM 8.0
and older have to use a dummy Driver instance.
Fixes #747.
This targets the release_1_3 branch, as thats the one I have tested. The
code around ClangResourcesDir has changed a little bit, but a forward
port should be trivial.
> Determine CLANG resources dir at runtime

- include/CL/CMakeLists.txt
- include/CL/cl.h
- include/CL/cl_d3d10.h
- include/CL/cl_d3d11.h
- include/CL/cl_dx9_media_sharing.h
- include/CL/cl_dx9_media_sharing_intel.h
- include/CL/cl_egl.h
- include/CL/cl_ext.h
- include/CL/cl_ext_intel.h
- include/CL/cl_gl.h
- include/CL/cl_gl_ext.h
- include/CL/cl_platform.h
- include/CL/cl_va_api_media_sharing_intel.h
- include/CL/cl_version.h
- include/CL/opencl.h
- lib/CMakeLists.txt
Update header files to match Khronos GitHub revision 0d5f18c6e7196863bc1557a693f1509adfcee056
Fixes #758
> Upstream OpenCL headers to latest Khronos rev.

- CHANGES
- config.h.in.cmake
- doc/sphinx/source/using.rst
- lib/CL/CMakeLists.txt
- lib/CL/clCreateCommandQueue.c
- lib/CL/clEnqueueNDRangeKernel.c
- lib/CL/clGetEventInfo.c
- lib/CL/clReleaseContext.c
- lib/CL/devices/devices.c
- lib/CL/devices/hsa/pocl-hsa.c
- lib/CL/pocl_cl.h
- lib/CL/pocl_cq_profiling.c
- lib/CL/pocl_cq_profiling.h
- lib/CL/pocl_mem_management.c
- lib/CL/pocl_mem_management.h
- lib/CL/pocl_runtime_config.h
- lib/CL/pocl_tracing.c
- lib/CL/pocl_tracing.h
- lib/CL/pocl_util.c
- lib/CL/pocl_util.h
- lib/llvmopencl/WorkitemHandler.cc
Setting POCL_PROFILING=1 collects kernel execution times and dumps stats atexit(). The purpose of this feature is to enable implementation of minimally intrusive profile collection; the profile data collector can choose the occasions when it gathers the time stamp data from the events. The impact to the observed execution profile is minimized by avoiding writing any logs, copying objects or such while collecting the data during execution.
It relies on the standard event timestamps to enable devices update them as (and when) they see fit during the execution.
The drawback is accumulation of cl_object garbage, which should be taken in account in the data collection interval; the collector should release the events and the extra data objects they hold often enough to avoid memory consumption …
> Add a minimally intrusive and easy-to-use kernel execution time profiler

- CHANGES
- lib/kernel/convert_type.cl
- lib/kernel/convert_type.py
Change replaces the original lo/hi decomposition of `convert_typeN(sourceN)` for a decomposition of the kind `(typeN)((type) source.s0, (type) source.s1, ... )`, which emits `sext`/ `zext` llvm IR opcodes (for integral types), which, in their turn, autovectorize nicely on ISAs with corresponding ops. Change addresses issue #796.
> refactor vector conversions for better autovectorizing codegen

- CREDITS
- lib/CL/clEnqueueNDRangeKernel.c
clEnqueueNDRangeKernel(): When hitting a `global_work_size := global_x * global_y * global_z` that equals `4 * preferred_wg_multiple * max_compute_units`, the program will now run in parallel (new behaviour) rather than not running in parallel (old behaviour).
- If `global_work_size` is smaller, the program will not run in parallel (unchanged).
- If `global_work_size` is bigger, the program will run in parallel (unchanged).
> Also split if the resulting group size is equal to the minimum group size

- lib/CL/clEnqueueNDRangeKernel.c
It looks like the 'kernel' parameter is used before is checked for nullness.
If you pass NULL as kernel argument to clEnqueueNDRangeKernel, the POCL library crashes.
This PR simply moves the nullness check before 'kernel' is actually used.
p.s.
I am not an OpenCL expert and new to this project, so maybe there is a reason I cannot see for this.
> Fix a crash when a null kernel object is passed to clEnqueueNDRangeKernel

- lib/CL/clEnqueueNDRangeKernel.c
- lib/CL/pocl_cq_profiling.c
These were causing some linking errors (undefined symbols) on my Linux system.
> Wrap calls to clRetainKernel and clRetainEvent

- examples/matrix1/matrix1.c
Required for RHEL 7.6 Power9/clang 9.0.
> matrix1: add missing #define

- lib/CL/pocl_llvm_build.cc
Fixes segfaults on powerpc. See https://github.com/pocl/pocl/issues/816#issuecomment-626269828
> Don't build with PIE enabled on powerpc

- lib/CL/devices/cuda/pocl-cuda.c
This makes the local/shared memory accesses using 32 bit pointers
> Pass --nvptx-short-ptr

- CHANGES
- lib/CL/devices/cuda/pocl-cuda-types.h
- lib/CL/devices/cuda/pocl-cuda.c
- lib/CL/devices/cuda/pocl-ptx-gen.cc
- lib/CL/devices/cuda/pocl-ptx-gen.h
- lib/CL/pocl_debug.h
- lib/CL/pocl_util.h
Turning it on prevents optimization opportunities.
Fixes #823
> Turn off automatic conversion of locals to args in CUDA

- tests/regression/CMakeLists.txt
I checked and these work fine on OSX.
> Enable regression tests on OSX

- CHANGES
- CREDITS
- lib/CL/pocl_llvm_utils.cc
- lib/CL/pocl_llvm_wg.cc
If POCL_VECTORIZER_REMARKS environment variable is set, print vectorizer remarks. Fixes issue #613
> Print loop vertorizer remarks when using poclcc

- CHANGES
- lib/llvmopencl/ParallelRegion.cc
- lib/llvmopencl/ParallelRegion.h
- lib/llvmopencl/WorkitemLoops.cc
- tests/regression/CMakeLists.txt
- tests/regression/test_issue_757.cpp
This change checks that loads in parallel loops are safe to execute
unconditionally before adding parallel loop metadata to the
instruction. LLVM makes this assumption. Without this change,
it's possible code can be generated that reads out of bounds
by the loop vectorizer.
See issue #757
> WI loops: ensure loads in parallel loops are safe to execute unconditionally

- lib/CL/devices/tce/tce_common.cc
As per OpenCL1.2 spec offset calculation should be as below.
src_origin[0] + src_row_pitch * src_origin[1] + src_slice_pitch * src_origin[2]
dst_origin[0] + dst_row_pitch * dst_origin[1] + dst_slice_pitch * dst_origin[2]
> TTASIM clEnqueueCopyBuffer offset correction

- lib/CL/devices/cuda/pocl-cuda.c
In contrast to `start` and `end`, `time_submit` is not based on a CUDA event
and sometimes represents a time stamp that is *after*`start` and `end`, leading to bogus event timings.
See e.g. https://github.com/illinois-ceesd/mirgecom/issues/71#issuecomment-678298984
> Fix event timing data for CUDA

- lib/CL/clCreateImage.c
[This](https://github.com/pocl/OpenCL-CTS/blob/4a6af23ff362cd95477abada53d85a948d394069/test_conformance/images/samplerlessReads/test_read_1D_buffer.cpp#L88) test case fails as `memobj->parent`, is not set if image type is `CL_MEM_OBJECT_IMAGE1D_BUFFER`
> CL_MEM_ASSOCIATED_MEMOBJECT Fix

- lib/CL/pocl_llvm_utils.cc
Configuring pocl with ENABLE_HOST_CPU_DEVICES=0 on a platform where llvm fails to recognize the host cpu leads to a situation where `get_llvm_cpu_name()` tries to get the host cpu from OCL_KERNEL_TARGET_CPU, which was never set in the first place. That produces an empty string which subsequently triggers an assert in `get_llvm_cpu_name()`.
> Avoid assert in get_llvm_cpu_name() when ENABLE_HOST_CPU_DEVICES=0 and llvm fails to recognize the host cpu

- lib/CL/devices/basic/basic.c
- lib/CL/devices/cpuinfo.c
OpenCL 3.0 has formalized the device vendor_id field, which should be the PCI vendor ID of the device if possible, and a value registered with Khronos (and automatically kept in sync cross-APIs) otherwise. This patchset tries to get the correct PCI vendor for both x86 and ARM CPUs based on the PCI root bus and/or the specific vendor, and prepares the ground (with a simple define that currently maps to the same value as before) for the Khronos registration as fall back.
> Vendor ID for 3.0

- lib/CL/pocl_llvm_utils.cc
- tests/regression/CMakeLists.txt
- tests/regression/test_issue_893.cpp
This PR will fix issue #893. The crash was caused by PoCL construction invalid parallel regions which don't follow single-entry single-exit policy. This happens because LLVM 11 onward jump threading pass is enabled by default in the front end when OpenCL kernel is compiled to IR before other PoCL passes run. IR contains duplicate blocks which will mess up parallel regions especially when kernel contain barriers.
To fix this for now I disabled jump threading pass with options it provides. There wasn't option to explicitly turn it off. I also left comment if this is enabled later then parallel region construction code might need some improvements and also to make sure using this pass doesn't disable other optimizations like vectorization. Maybe also running this pass later after PoCL passes …
> Disable jump threading pass from crashing pocl with LLVM 11 and 12

- CMakeLists.txt
- cmake/LLVM.cmake
- examples/vecadd/CMakeLists.txt
- include/pocl.h
- include/pocl_export.h
- lib/CL/devices/basic/basic.c
- lib/CL/devices/common.c
- lib/CL/devices/common.h
- lib/CL/devices/cpuinfo.h
- lib/CL/devices/devices.c
- lib/CL/devices/devices.h
- lib/CL/devices/pocl_local_size.h
- lib/CL/devices/prototypes.inc
- lib/CL/devices/pthread/pthread_utils.c
- lib/CL/devices/topology/pocl_topology.h
- lib/CL/pocl_cache.c
- lib/CL/pocl_debug.c
- lib/CL/pocl_debug.h
- lib/CL/pocl_llvm.h
- lib/CL/pocl_llvm_api.h
- lib/CL/pocl_runtime_config.h
- lib/CL/pocl_timing.c
- lib/CL/pocl_util.h
- tests/CMakeLists.txt
- tests/runtime/CMakeLists.txt
- tests/runtime/test_dlopen.c
- tests/workgroup/CMakeLists.txt
Here I have a patch series to finally allow building with `-fvisibility=hidden -fvisibility-inlines-hidden` to reduce the amount of (mostly c++) symbols exposed by the shared libraries. It starts with some fixes I've long been carrying in the Debian packages and some further cleanup (e.g. pocl symbols should be prefixed with `pocl` and tests should depend on `pocl_version_check`).
Please merge or cherry-pick as much as you like and we can continue working on the remaining parts.
I've only tested it with the CPU devices (`basic` and `pthread`) and only with building an ICD and testing with pocl's internal testsuite. There may be adjustments needed for other build configurations, e.g. more declarations needing a `POCL_EXPORT` decoration. (I've tried to keep the `pocl_*` symbols exposed …
> support building with -fvisibility=hidden -fvisibility-inlines-hidden

- lib/CL/pocl_llvm_build.cc
https://github.com/llvm/llvm-project/commit/c495dfe0268bc2be8737725d657411baa1399e9d
> Fixed LLVM 12 support: clang::CompilerInvocation::setLangDefaults signature was changed

- lib/CL/pocl_cq_profiling.c
This is achieved by adding !total_commands to the divisor, which is a
quick way to divide by 1 if total_commands is 0, and by total_commands
itself if total_command is non-zero.
This should fix #909
> Avoid division by 0 in profiling output if total_commands is 0

- lib/CL/devices/cpuinfo.c
If sysfs is not mounted (or not available, e.g. on BSD), fopen() will return a NULL pointer and this will be passed to fscanf, potentially resulting in NULL dereference. This fixes a segmentation fault running poclcc -l on NetBSD.
> cpuinfo: check for fopen() failure when opening sysfs nodes

- lib/CL/pocl_timing.c
CLOCK_UPTIME_FAST is an extension only available on FreeBSD and DragonFlyBSD, so don't try to use it on other BSDs - this previously resulted a compilation failure on NetBSD.
Instead, use CLOCK_MONOTONIC. This is available on NetBSD and OpenBSD and is defined in POSIX.2008. On older Unix-like operating systems, keep the fallback to CLOCK_REALTIME.
Replace OS-specific checks with more portable checks for definitions.
> pocl_timing: fix detection of Unix monotonic clocks

- CMakeLists.txt
- config.h.in.cmake
- lib/CL/devices/basic/basic.c
- lib/CL/devices/common.c
- lib/CL/devices/devices.c
- lib/CL/devices/hsa/pocl-hsa.c
- lib/CL/devices/pthread/pthread.c
- Many Unix systems do not need (macOS, Linux with musl?), or do  not have (most BSDs) libdl, and dlopen() is in libc instead.  Therefore, libdl being missing should not be fatal.   Replace checks for libdl.so with checks for dlfcn.h.
- Remove #error checks for libdl from indivial C files. The CMake build system will already refuse to run if dlopen()  is missing, so these checks are redundant.
Helps with building on NetBSD.
> Fix detection of dlopen()/libdl

- lib/llvmopencl/ParallelRegion.cc
Now that parallel loop metadata if-conversion safety is removed by [this](https://reviews.llvm.org/D103907) change for LLVM 13 branch. This change will enable adding metadata insertion on load instructions unconditionally. Prior to LLVM 13 will still use conditional placement of metadata to avoid miscompilations. This change is a follow-up to #850.
I tested this locally and with the fix using latest LLVM from trunk is not producing illegal code anymore. Also earlier vectorization failures from PolyBench kernels [this](https://github.com/cavazos-lab/PolyBench-ACC/blob/master/OpenCL/stencils/convolution-3d/3DConvolution.cl) and [this](https://github.com/cavazos-lab/PolyBench-ACC/blob/master/OpenCL/stencils/convolution-2d/2DConvolution.cl) are now vectorizing successfully and executing …
> Add parallel loop metadata on LLVM 13 onward for load instructions inside conditions

- lib/llvmopencl/ParallelRegion.cc
Follow-up PR for this #951. This time lower the LLVM version check to 12 because the fix got backported to LLVM 12 release branch llvm/llvm-project@b690ec5.
> Add parallel loop metadata on LLVM 12 onward and not before on load instructions inside conditions

- CHANGES
- CMakeLists.txt
- CREDITS
When CMAKE_BUILD_TYPE=DEBUG, the linking memory usage is so
high the build fails without setting -j <low_num> on the command
line.
The llvm project has a similar problem which is solved on the
ninja buildsystem by splitting the compile and link jobs.
see llvm-project/llvm/cmake/modules/HandleLLVMOptions.cmake
and these variables
LLVM_PARALLEL_COMPILE_JOBS and LLVM_PARALLEL_LINK_JOBS
The new POCL equivelent variables are
PARALLEL_COMPILE_JOBS and PARALLEL_LINK_JOBS
ex/ used in the cmake configure step
cmake -G Ninja
-DPARALLEL_COMPILE_JOBS=16
-DPARALLEL_LINK_JOBS=8
And reported if used as status
...
-- OCS_AVAILABLE: ON
-- PARALLEL_COMPILE_JOBS: 16
-- PARALLEL_LINK_JOBS: 8
-- POCL_ICD_ABSOLUTE_PATH: ON
...
> [cmake] use ninja's compile and link pools

- lib/CL/pocl_timing.c
> pocl_gettimemono_ns: use ULL suffix for int64_t

- tests/CMakeLists.txt
this allows to run tests when cross compiling (eg mingw)
> cmake: use add_test NAME/COMMAND args

- examples/example2/example2.c
- examples/example2a/example2a.c
- examples/matrix1/matrix1.c
- include/poclu.h
- include/vccompat.hpp
- lib/CL/clCreateContextFromType.c
- lib/CL/clCreateKernel.c
- lib/CL/clEnqueueNDRangeKernel.c
- lib/CL/clGetPlatformInfo.c
- lib/CL/clReleaseProgram.c
- lib/CL/devices/common.c
- lib/CL/devices/cpuinfo.c
- lib/CL/devices/devices.c
- lib/CL/devices/pthread/pthread.c
- lib/CL/pocl_build.c
- lib/CL/pocl_cache.c
- lib/CL/pocl_cl.h
- lib/CL/pocl_file_util.c
- lib/CL/pocl_timing.c
- lib/CL/pocl_util.c
- tests/kernel/kernel.c
- tests/regression/test_flatten_barrier_subs.cpp
- tests/runtime/CMakeLists.txt
- tests/runtime/test_event_cycle.c
With this I succeeded in building libpocl.dll and the tests.
Now vccompat.hpp is used also for mingw because many things are shared with the msvc path.
It should help to build on MSVC as some common paths were fixed.
Yet to figure out why the loader fails.
> Fix build on MinGW

- examples/PyOpenCL/configure.sh
--no-site-packages option has been removed from latest versions of python virtualenv causing PyOpenCL testsuite error out during make prepare_examples. 
Only information about this option I found from python3 virtualenv version 16.7.9 where this command is already deprecated and its functionality is the default behavior. 
[https://virtualenv.pypa.io/en/legacy/reference.html#cmdoption-no-site-packages]
> Removed deprecated option from PyOpenCL testsuite configurations

- CMakeLists.txt
This allows to avoid build failures when using qemu user mode for riscv64 [1]:
the corresponding bug in qemu [2] will get fixed but handling that here allows
to keep pocl buildable by old qemu versions.
[1]: https://bugs.launchpad.net/ubuntu/+source/pocl/+bug/1942895
[2]: https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1942884
Signed-off-by: Alexandre Ghiti <alexandre.ghiti@canonical.com>
> CMakeLists.txt: Handle 'undefined' values returned by getconf

- lib/CL/devices/cuda/pocl-cuda.c
- lib/CL/devices/hsa/pocl-hsa.c
- lib/CL/devices/proxy/pocl_proxy.c
- lib/CL/devices/pthread/pocl-pthread_scheduler.h
- lib/CL/devices/pthread/pthread.c
- lib/CL/devices/pthread/pthread_scheduler.c
- lib/CL/devices/pthread/pthread_utils.c
- lib/CL/devices/tce/tce_common.cc
- lib/CL/devices/tce/ttasim/ttasim.cc
- lib/CL/devices/vulkan/pocl-vulkan.c
- lib/CL/pocl_cl.h
- lib/CL/pocl_util.c
- lib/CL/pocl_util.h
some fixes for the pthread device, mainly:
* `pthread_scheduler_init()`: `abort()` if `pthread_create()` fails (also if it fails with `EAGAIN`)
* recovery would be hard: terminate the partially created thread pool and return an error code
* if any worker thread experienced an allocation failure during initialization, don't assert, but report this back to the scheduler: uninitialize the scheduler (shut down the worker thread pool) in this case and return an error code from  `pthread_scheduler_init()`
this may not totally solve the original issue, but at least in case of only the allocations failing the application would have the possibility to handle the unavailable device
there are more `pthread_create()` and other `pthread_*()` calls missing error handling in the pocl codebase, these are …
> Pthread fixes

- lib/llvmopencl/ParallelRegion.cc
- lib/llvmopencl/ParallelRegion.h
Use composition instead of inheritance.
> Avoid inheritance from std::vector in ParallelRegion class.

- CHANGES
- CREDITS
- lib/CL/devices/cuda/pocl-cuda.c
The current code implicitly converts `epoch` to a float before calculating `time_end` and `time_start` and converting back to a `cl_ulong`. A `float` only has seven or so digits of accuracy meaning this conversion throws away the least significant digits of `epoch` if `epoch` is larger than about 1e8. Conversely, the precision of `diff` is around 1e-3 so multiplying by 1e6 makes all of these digits > 1 and converting this number to a `cl_ulong` will not lose any  digits. The gist below illustrates this in Python.
https://gist.github.com/nchristensen/15ab1fd53ba099accaab780ab6dbad90
> Avoid loss of precision in CUDA event time calculations

- lib/CL/pocl_llvm_wg.cc
- lib/llvmopencl/Workgroup.cc
As of llvm 14, LLVMBuildCall is deprecated in favor of LLVMBuildCall2
> llvm 14: handle deprecated LLVMBuildCall

- include/CL/cl_ext.h
This value was initially fixed by #917 but got reverted by #931 (specifically https://github.com/pocl/pocl/commit/5f806ca03228f6c4ab4a3a3042dd4475913125a5).
cc: @Vinsteri
> Fix value of CL_DEVICE_PCI_DOMAIN_ID_NV

- lib/CL/devices/common_driver.c
- lib/CL/devices/common_driver.h
- lib/CL/devices/prototypes.inc
- lib/CL/devices/vulkan/pocl-vulkan.c
Remove `const` qualifier on the declaration of the `length` parameter of `pocl_*_supports_binary` functions.
This silences `clang-tidy` and makes the code more consistent.
> Remove redundant `const` qualifier on parameter declarations

- lib/CL/devices/cuda/pocl-cuda.c
This fixes a bug we found in #890
> Fix freeing for devices that don't support cuMemHostRegister

- CMakeLists.txt
When explicit full paths are provided for BINDIR, LIBDIR, etc, like is the case in [Nix](https://nixos.org/), they would get the prefix prepended to them regardless, which is wrong:
```
/nix/store/g2lx5mamf4dapv52w91r98c69vcc7glq-pocl-1.8
├── nix
│  └── store
│     └── g2lx5mamf4dapv52w91r98c69vcc7glq-pocl-1.8
│        ├── bin
│        │  └── poclcc
│        ├── include
│        │  └── CL
│        │     ├── cl.h
│        │     ├── cl2.hpp
│        │     ├── cl_d3d10.h
│        │     ├── cl_d3d11.h
│        │     ├── cl_dx9_media_sharing.h
│        │     ├── cl_dx9_media_sharing_intel.h
│        │     ├── cl_egl.h
│        │     ├── cl_ext.h
│        │     ├── cl_ext_intel.h
│        │     ├── cl_ext_pocl.h
│        │     ├── cl_gl.h
│        │     ├── cl_gl_ext.h
│        │     ├── …
```
> build: avoid duplicating prefix in install paths by using full paths

- lib/CL/devices/cuda/pocl-cuda.c
This limit is imposed by ptxas, and is the same value
returned by NVidia CL.
> CUDA: Set max_parameter_size to correct value

- lib/CL/devices/cuda/pocl-ptx-gen.cc
In OpenCL, `__kernel` functions can have `__constant` pointers and CUDA
doesn't allow that. So POCL needs to copy those from `__global`
to `__constant` memory region before calling the CUDA kernel.
These are copied to `_constant_memory_region_`. Since this buffer
is set externally to the CUDA module, need to mark it as external
linkage.
Fixes https://github.com/pocl/pocl/issues/1047
> Mark _constant_memory_region_ as external linkage with no initializer

- lib/CL/clGetPlatformInfo.c
Add throw assert error if result of pocl_cl_name_version_to_str does not fit in buffer
> throw assert error if extension string is too long

- CREDITS
- lib/CL/devices/devices.c
If a device driver allocates resources in `pocl_<device>_init_ops`,
calling it twice can result in a memory leak.
Also, don't append the path separator twice when building the path
to the device's DSO.
This is a clone of https://github.com/pocl/pocl/pull/1050 which was closed because I accidently removed the fork^^
Also added myself to the credits list, as was suggested.
> Don't call pocl_<device>_init_ops twice

- lib/CL/clEnqueueSVMMigrateMem.c
- lib/CL/devices/common.c
Removes a duplicate check and fixes the event tracing string.
> minor clEnqueueSVMMigrateMem fixes

- lib/CL/devices/vulkan/pocl-vulkan.c
Due to its experimental nature, the Vulkan driver does not probe for
devices unless included on POCL_DEVICES, but this was done incorrectly:
checking for pocl_device_get_env_count() < 0 only tells if POCL_DEVICES
was set or not, not if VULKAN was actually present in the env string.
Hence, Vulkan was disabled if POCL_DEVICES was unset, but enabled if
POCL_DEVICES was set, regardless of whether it included the string
'VULKAN' in it or not, so e.g. `POCL_DEVICES=basic clinfo -l` would show
all Vulkan devices in addition to the basic device.
Fix this by checking for env_count <= 0 instead. This allows us to avoid
probing for Vulkan devices if no Vulkan devices are requested. If VULKAN
was requested in POCL_DEVICES, we still return all Vulkan devices (not
just the first requested number). This …
> Don't probe for Vulkan devices if not requested

- lib/CL/clGetDeviceAndHostTimer.c
- lib/CL/clGetHostTimer.c
- lib/CL/clGetKernelSubGroupInfo.c
- lib/CL/clGetPipeInfo.c
- lib/CL/clSetProgramReleaseCallback.c
Resolve several cts linking errors against the standalone libOpenCL
by exporting some function calls.
> ocl3 : export some functions calls

- lib/CL/clEnqueueSVMFree.c
- lib/CL/devices/common.c
- lib/CL/pocl_util.c
The spec for [`clEnqueueSVMMemFree`](https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_API.html#clEnqueueSVMFree) says:
> The memory associated with `svm_pointers` can be reused or freed after the function returns.
AFAICT, the current code in pocl simply holds onto the memory passed in by the user, which I believe is not conformant behavior. This change makes a copy instead.
cc @matthiasdiener
> `clEnqueueSVMMemFree`: copy pointers

- cmake/LLVM.cmake
- include/_kernel.h
- include/_libclang_versions_checks.h
Clang 16 is in development.
In 16, typed pointer support will be removed.
So this infra is needed to work on opaque pointer before the release
> Add build infra for clang 16

- include/_libclang_versions_checks.h
- lib/CL/pocl_llvm_wg.cc
- tests/tce/fp16/CMakeLists.txt
The define LLVM_OLDER_THAN_6_0 means llvm 5 or older.
The toplevel CMakeList.txt prohibits this, so remove the
definition and use of this macro.
> Remove LLVM_OLDER_THAN_6_0

- lib/CL/clCreateBuffer.c
- lib/CL/clCreateCommandQueue.c
- lib/CL/clCreateContext.c
- lib/CL/clCreateImage.c
- lib/CL/clCreateKernel.c
- lib/CL/clReleaseCommandQueue.c
- lib/CL/clReleaseContext.c
- lib/CL/clReleaseDevice.c
- lib/CL/clReleaseEvent.c
- lib/CL/clReleaseKernel.c
- lib/CL/clReleaseMemObject.c
- lib/CL/clReleaseProgram.c
- lib/CL/clReleaseSampler.c
- lib/CL/clRetainCommandQueue.c
- lib/CL/clRetainContext.c
- lib/CL/clRetainDevice.c
- lib/CL/clRetainEvent.c
- lib/CL/clRetainKernel.c
- lib/CL/clRetainMemObject.c
- lib/CL/clRetainProgram.c
- lib/CL/clRetainSampler.c
- lib/CL/pocl_llvm_utils.cc
- lib/CL/pocl_util.c
This makes it easier to follow the life cycles of objects
instead of looking at addresses.
This is very useful when looking at reference counts.
objects changed:
* buffer
* command queue
* context
* device
* image
* kernel
* program
* sampler
> Debug: add IDs to debug messages

- lib/CL/devices/cuda/pocl-cuda.c
The header is not needed, and since it's inclusion causes issues with older Cuda versions, remove it for now.
> Cuda: remove unused nvPTXCompiler header

- CMakeLists.txt
- config.h.in.cmake
- lib/llvmopencl/LLVMUtils.h
- lib/llvmopencl/Workgroup.cc
- lib/llvmopencl/WorkitemLoops.cc
- lib/llvmopencl/linker.cpp
clang is moving to typeless, opaque pointers
clang-14 warns about some deprecations.  These are a subset of
what must be done for clang-15. So clean them up in 14.
see
https://llvm.org/docs/OpaquePointers.html
> clang-14: handle deprecated warnings for opaque ptr

- lib/CL/devices/tce/ttasim/ttasim.cc
This was left to 0, which is non-compliant. 
After this, the basic PyOpenCL code seems to run.
> ttasim: Initialize CL_DEVICE_MAX_PARAMETER_SIZE

- config.h.in.cmake
- lib/CL/devices/tce/tce_common.cc
- lib/CL/devices/tce/ttasim/ttasim.cc
Two commits:
1. Fix the tce-driver to not call "bare" tcecc, but instead propagate the binary name from CMake.
2. Add old timestamping code to update_event callback. This is an old feature that seems to have not been propagated to here yet.
> TCE driver fixes

- lib/CL/devices/tce/ttasim/ttasim.cc
fix a bug where standalone global buffers were written to AS 0 instead of global
> TCE: standalone mode bug fix

- lib/CL/devices/almaif/CMakeLists.txt
Also removed the separate std-arg, since it's only for TCE compatibility and will come from TCE_CXXFLAGS.
This attempts to fix @pjaaskel 's bug:
>The build of AlmaIF (when I enable it) fails with:
>
>g++: error: unrecognized debug output level ‘ -O3 -Wall -Wextra -Wno-long-long  -std=c++14’
>
>The Cmake does some trickery? My CXXFLAGS is -g -O3 -Wall -Wextra -Wno-long-longso it likely converts it to -g'-O3 -Wall >-Wextra -Wno-long-long' somehow?
> AlmaIF: guard TCE compile options in no-TCE builds

- doc/www/pocl-publications.txt
- doc/www/pocl-using-publications.txt
The split between 'core' and 'using'-publications is a bit arbitrary, I thought to split it based on whether the publication added code/features to the open-source or not.
> Add some PoCL publications to the website

- lib/CL/clCommandCopyBufferKHR.c
- lib/CL/clCommandCopyBufferRectKHR.c
- lib/CL/clCommandCopyBufferToImageKHR.c
- lib/CL/clCommandCopyImageKHR.c
- lib/CL/clCommandCopyImageToBufferKHR.c
- lib/CL/clCommandFillBufferKHR.c
- lib/CL/clCommandFillImageKHR.c
- lib/CL/clCreateCommandBufferKHR.c
- lib/CL/clEnqueueCommandBufferKHR.c
- lib/CL/clReleaseCommandBufferKHR.c
- lib/CL/clReleaseEvent.c
- lib/CL/pocl_cl.h
- lib/CL/pocl_img_buf_cpy.c
- lib/CL/pocl_ndrange_kernel.c
- lib/CL/pocl_util.c
Fixes #1108
It seems events were just a red herring, the real culprit of the memory leak appears to have been that required mem objects are stored in two different places depending on whether the command is recorded to a command buffer or enqueued immediately. The latter store the list of mem objects in the event and release them in `pocl_update_event_finished` while the former store the list in the command node directly and release the mem objects only when the command is freed along with the command buffer it was recorded to.
Can you confirm that this patch fixes the problem @franz ? If it does then it's probably best to take some time to unify the mem object handling between the two code paths.
> Fix excessive retaining of mem objects

- lib/CL/devices/almaif/almaif.cc
Almaif used type_size to check for the scalar size which returns 0 if it cannot find the type from
pocl_llvm_metadata.c's type_data_map. This was happening for e.g. typedeffed scalar arguments. 
Now instead use the size coming from clSetKernelArg.
> Almaif: fix argbuffer scalar sizes

- lib/CL/devices/tce/ttasim/ttasim.cc
If adfFile would not contain a slash strrchr will return NULL, which causes undefined behavior in snprintf (usually printing "(null)"). We can just use the file as-in in this case.
> ttasim: Fix name generation

- examples/accel/CMakeLists.txt
Test that can be run on the pynq device had a typo in the poclbin path
> Almaif: fix example0 poclbin path

- examples/PyOpenCL/CMakeLists.txt
- examples/conformance/CMakeLists.txt
- include/CL/cl.h
- include/CL/cl_d3d10.h
- include/CL/cl_d3d11.h
- include/CL/cl_dx9_media_sharing.h
- include/CL/cl_ext.h
- include/CL/cl_gl.h
- include/CL/cl_icd.h
- include/CL/cl_platform.h
Bump PyOpenCL to its latest release since the previous one does not build on Ubuntu 22.10.
Switch conformance test suite from the external fork to the latest upstream tag & update OpenCL headers from upstream so the updated CTS builds. NB: the CTS seems to fail to build when configured as a Release build (see KhronosGroup/OpenCL-CTS#1582)
> Testsuite fixes

- lib/CL/devices/almaif/almaif.cc
Check which address region the address does belong to and use the base address of it, instead of always assuming it points to DMEM.
> AlmaIF: Fix relativ addressing for external memory

- lib/CL/clCreateKernel.c
The debug message "Created kernel ..." would be printed even when the kernel name was invalid. In this case `kernel` is null, leading to a segfault.
> clCreateKernel: Fix segfault with invalid kernel name

- lib/CL/clCreateCommandBufferKHR.c
This is needed on macOS where PTHREAD_MUTEX_INITIALIZER is not zero.
> Initialize the command_buffer_khr mutex

- lib/CL/pocl_debug.h
Without this the build fails with the following error when built without POCL_DEBUG_MESSAGES:
```
../lib/CL/devices/almaif/MMAPRegion.cc: In constructor ‘MMAPRegion::MMAPRegion(size_t, size_t, int)’:
../lib/CL/devices/almaif/MMAPRegion.cc:43:3: error: ‘POCL_MSG_PRINT_ALMAIF_MMAP’ was not declared
in this scope; did you mean ‘POCL_MSG_PRINT_ALMAIF2’?
43 |   POCL_MSG_PRINT_ALMAIF_MMAP(
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~
|   POCL_MSG_PRINT_ALMAIF2
```
and about 10 more.
> Add stub macro POCL_MSG_PRINT_ALMAIF_MMAP without POCL_DEBUG_MESSAGES

- CHANGES
- CMakeLists.txt
- examples/conformance/CMakeLists.txt
- lib/CL/clGetDeviceInfo.c
- lib/CL/clGetKernelSubGroupInfo.c
- lib/CL/clGetPlatformIDs.c
- lib/CL/devices/basic/basic.c
- lib/CL/devices/common.c
- lib/CL/devices/pthread/pthread.c
- lib/kernel/CMakeLists.txt
- lib/kernel/host/CMakeLists.txt
- lib/kernel/subgroups.c
- lib/kernel/subgroups.cl
- lib/llvmopencl/Kernel.cc
- lib/llvmopencl/Kernel.h
- lib/llvmopencl/WorkitemLoops.cc
- lib/llvmopencl/WorkitemLoops.h
- tools/scripts/format-branch.sh
- tools/scripts/format-last-commit.sh
The subgroup is always the X dimension, and there is only one subgroup in flight at the same time. Thus there are Z*Y SGs per WG. It passes the CTS test even though independent progress is not supported because there's only one SG in flight at the same time making progress.
Also preliminary shuffle and ballot implementations which work only with uniform execution for now.
The cross-WI data exchange is implemented via __pocl_{wg,local_mem}_alloca(), an internal function that allocates "local memory" (thread stack) dynamically.
> Basic cl_khr_subgroups implementation for CPU

- bin/poclcc.c
- examples/example1/example1.c
- lib/CL/devices/almaif/EmulationDevice.cc
- lib/CL/devices/almaif/almaif.cc
- lib/CL/pocl_build.c
- poclu/misc.c
- poclu/poclu.h
- tests/runtime/test_buffer_migration.c
- tests/runtime/test_buffer_ping_pong.c
* poclcc support for cl_device_type_custom
* couple new lines in error messages of almaif
* poclu_get_multiple_devices has toggle for custom devices
* poclu_get_any_device_2 will look for custom if no normal found
* device kernel hashes are also calculated for builtin kernels (pthread bi)
> Almaif: qol fixes

- include/_builtin_renames.h
- lib/kernel/CMakeLists.txt
- lib/kernel/SPIR/generate_spir_wrapper.py
- lib/kernel/fmax_common.cl
- lib/kernel/fmin_common.cl
- lib/kernel/host/CMakeLists.txt
Fixes #1172 
Adds support for the SPIR-V `fmin_common` and `fmax_common` extended instructions.
Signed-off-by: Ben Ashbaugh <ben.ashbaugh@intel.com>
> add support for SPIR-V fmax_common and fmin_common

- CHANGES
- doc/sphinx/source/debug.rst
- lib/kernel/host/CMakeLists.txt
- lib/kernel/printf.c
...instead of waiting for the end of the kernel command. This makes it (again) useful for debugging kernel segfaults.
> CPU devices: flush printf() output after each call

- CHANGES
- lib/CL/devices/cuda/pocl-cuda.c
In which the [improved FluidX3D](https://github.com/ProjectPhysX/FluidX3D/tree/experimental-p2p) runs on an 8 GPU setup* 3.6x as fast as with the Nvidia proprietary OpenCL driver.
It seems Nvidia's driver takes a huge performance hit if buffers are migrated between devices, as the previous FluidX3D release (2.4) runs much better despite doing buffer migrations manually by downloading buffer contents to host memory and reuploading to the target device. Still, even compared to the old approach this new FluidX3D running on PoCL-CUDA with this patch applied is 2.0x faster.
In other words, this massively improves multi-GPU scaling of PoCL-CUDA (but does not affect single GPU performance in any way).
Some unrelated fixes to PoCL-CUDA are still needed to make FluidX3D interactive graphics work …
> cuda: use PCIe P2P copies when migrating between cuda devices

- doc/sphinx/source/almaif.rst
- doc/sphinx/source/install.rst
`accel.rst` [had](https://github.com/pocl/pocl/commit/74b46f46be9c8205e1931983164c7f6770f96c2a) such a note. I don't know why it was not copied to current document
> update install.rst to note specifying random hash in case of almaif devices

- lib/CL/devices/pthread/pthread_scheduler.c
- lib/CL/pocl_util.h
> Fix runtime error 'undefined symbol: pocl_ignore_sigfpe_for_thread' on aarch64

- examples/accel/OpenCLcontext.cpp
This is because of C++11 compatibility reasons.
Fixes #1200.
> Don't use make_unique in countred example

- lib/llvmopencl/LLVMUtils.cc
isGVarUsedByFunction() must recursively search functions to check usage of a GVar, because it is called by isAutomaticLocal(), which in turn is called on "unprocessed" LLVM bitcode (or SPIRV) = PoCL hasn't run any LLVM passes yet; in particular the pass that inlines all functions using "special" variables and kernels hasn't been run.
> Fix a bug in commit 54a55106527 (add a check to isAutomaticLocal)

- examples/EinsteinToolkit/CMakeLists.txt
- lib/llvmopencl/Workgroup.cc
Let's see if the compile time explosion is still there with the latest LLVMs.
> Retain the AddAliasScopeMetadata

- .github/workflows/build_cmake.yml
- lib/kernel/host/addrspace_operators.ll
- lib/llvmopencl/linker.cpp
Special handling for the AS cast built-ins: They do not type mangling, which complicates the CPU implementation which sometimes gets all-0 AS input and sometimes not (SPIR-V). Here, in case the target doesn't define these built-ins in the bitcode library, we replace the calls directly with address space casts. This works for uniform address space targets (CPUs), while the disjoint AS targets can override the implementation as needed. Fixes #1203.
> CPU: Replace OpenCL as cast builtins with addrspace casts

- lib/CL/devices/cuda/pocl-cuda.c
- lib/CL/devices/tce/ttasim/ttasim.cc
- lib/CL/pocl_cl.h
- lib/CL/pocl_llvm_build.cc
CUDA OpenCL compiler also has -ffp-contract=fast by default
Fixes https://github.com/pocl/pocl/issues/1225
> Fix FFP contract flag and make CUDA default to fast

- lib/CL/clGetCommandBufferInfoKHR.c
removed unnecessary `&` which causes crashes during `memcpy` operation
> Corrected clGetCommandBufferInfoKHR with CL_COMMAND_BUFFER_QUEUES_KHR query

- lib/CL/devices/common.c
- lib/CL/devices/cpuinfo.c
- lib/CL/pocl_cl.h
- lib/CL/pocl_llvm.h
- lib/CL/pocl_llvm_build.cc
- lib/CL/pocl_llvm_utils.cc
These patches have been part of the Debian packages for more than a year already with no known problems.
With my distribution maintainer hat on ... I like the PoCL distro build (performance wise, makes good use of the cpu) and at the same time dislike compiling stuff for the native target since it may make debugging target dependent bugs difficult (not that I'm aware of any such bug, yet). Also the tests only cover one of the many targets of the distro build - that best matches the buildd CPU.
Targets that require only a subset of the features provided by the host CPU should be testable on that machine, too. E.g. a CPU capable of AVX512 can test SSE2 (only), AVX, AVX2, ... too.
I've therefore implemented some changes ... allowing overriding the CPU detection at runtime (but only to …
> cpu selection

- examples/example1/CMakeLists.txt
- examples/example2/CMakeLists.txt
- examples/example2a/CMakeLists.txt
> examples: fix cmake error caused by `-E rm` option

- include/rename_opencl.h
This allows access to pocl extensions in scenarios where you make use of rename_opencl.h
> proxy: add pocl extensions to rename_opencl.h

- lib/CL/pocl_util.c
some devices (like the basic device) do not have
a wait_event function
@jansol here is the fix we discussed
> util: call clWaitForEvents for content size migrations

- lib/CL/devices/remote/CMakeLists.txt
- lib/CL/devices/remote/communication.c
- lib/CL/pocl_networking.c
- lib/CL/pocl_networking.h
- pocld/CMakeLists.txt
- pocld/common.cc
- pocld/common.hh
- pocld/peer_handler.cc
- pocld/pocld.cc
- pocld/rdma.cc
This should unify the behaviour everywhere, particularly when passing `localhost` or `ip6-localhost` as the server address. Also deduplicated the client socket options setting code while I was at it.
Fixes #1304
> remote+pocld: deduplicate hostname resolution and socket options code

- lib/CL/pocl_build.c
- lib/kernel/subgroups.c
- lib/kernel/subgroups.cl
Small fixes to enable offloading OpenVINO across PoCL-R. Also a few initial fixes to make OpenVINO kernels run on PoCL-CPU. It lacks at least the half precision image datatype handling still for that part.
> OpenVINO fixes

- lib/CL/devices/basic/basic.c
- tools/scripts/format-branch.sh
- tools/scripts/format-last-commit.sh
Events are notified in locked state so unlock them before scheduling which tries to notify them again which in turn tries to lock the event.
> basic: don't assume other threads won't notify events

- lib/CL/clGetContextInfo.c
According to the OpenCL spec, param_value_size_ret may be NULL and should be ignored in that case. This commit fixes one case that did not check if the pointer is NULL before writing to it.
> clGetContextInfo: param_value_size_ret may be NULL

- CMakeLists.txt
- include/CL/cl_ext_pocl.h
- include/messages.h
- include/pocl.h
- lib/CL/clCreateBuffer.c
- lib/CL/clGetMemObjectInfo.c
- lib/CL/devices/common.c
- lib/CL/devices/common_driver.c
- lib/CL/devices/remote/communication.c
- lib/CL/devices/remote/communication.h
- lib/CL/devices/remote/remote.c
- lib/CL/pocl_cl.h
- lib/CL/pocl_debug.c
- lib/CL/pocl_networking.c
- lib/CL/pocl_util.h
- pocld/common.hh
- pocld/shared_cl_context.cc
- pocld/shared_cl_context.hh
- pocld/virtual_cl_context.cc
- tests/runtime/CMakeLists.txt
- tests/runtime/test_pinned_buffers.cpp
- tools/scripts/run_remote_tests
This is a first step to support raw pointer-type of memory management on remote. It provides cudaMalloc()-level of functionality where the implementation can return a device pointer without needing to map it to the host virtual memory. It's done via an experimental `pocl_pinned_buffers` extensions to the basic clCreateBuffer() API: With CL_MEM_PINNED, the buffer is allocated permanently to the device's global memory with a fixed address until the buffer is freed. The address can be queried with clGetMemObjectInfo().
This (to my understanding) should be sufficient to also support minimal (buffer based) SYCL with AdaptiveCpp.
It's implemented for PoCL-CPU by trivially setting the device address to the allocated host ptr. PoCL-remote uses the target driver's coarse grained SVM for the …
> cl_pocl_pinned_buffers: Experimental extension for cl_mem pinning

- .github/workflows/build_cmake.yml
- lib/CL/devices/remote/communication.c
- lib/CL/devices/remote/communication.h
- lib/CL/pocl_networking.c
- pocld/CMakeLists.txt
- pocld/cmd_queue.cc
- pocld/common.cc
- pocld/common.hh
- pocld/peer.cc
- pocld/peer_handler.cc
- pocld/pocld.cc
- pocld/rdma.cc
- pocld/rdma.hh
- pocld/rdma_request_th.cc
- pocld/reply_th.cc
- pocld/request.cc
- pocld/request.hh
- pocld/request_th.cc
- pocld/virtual_cl_context.cc
- tests/runtime/CMakeLists.txt
- tools/scripts/format-branch.sh
- tools/scripts/format-diff.sh
- tools/scripts/format-last-commit.sh
- tools/scripts/run_remote_tests
- tools/scripts/test_remote_runner_multi.sh
- tools/scripts/test_remote_runner_single.sh
- tools/scripts/test_remote_runner_with_local.sh
Move from per-client per-socket threads to a single thread that `poll()`s all client sockets. Additionally requests are now read incrementally to avoid large requests from blocking smaller commands.
> Pocld socket rework

- include/messages.h
- include/pocl.h
- lib/CL/clEnqueueSVMUnmap.c
- lib/CL/devices/bufalloc.c
- lib/CL/devices/bufalloc.h
- lib/CL/devices/remote/communication.c
- lib/CL/devices/remote/communication.h
- lib/CL/devices/remote/remote.c
- pocld/CMakeLists.txt
- pocld/cmd_queue.cc
- pocld/common.hh
- pocld/request.cc
- pocld/shared_cl_context.cc
- pocld/shared_cl_context.hh
- pocld/virtual_cl_context.cc
- tests/runtime/CMakeLists.txt
- tests/runtime/test_svm.cpp
Still a WiP so disabled in code meanwhile. It currently works only if both the server and the client manage to map the SVM pool to the same address range. This seems to happen often enough for this state to be useful for testing and further development.
> Initial steps for CG SVM on PoCL-R

- CMakeLists.txt
- lib/CL/devices/cuda/pocl-cuda.c
This patchset removes a header double inclusion, and adds the `__opencl_c_images` extension to the ones declared by the CUDA devices, to work around the upstream `opencl-c.h` header issue discussed in issue #1339.
> CUDA fixes

- lib/CL/CMakeLists.txt
- lib/CL/clCloneKernel.c
- lib/CL/clCreateBuffer.c
- lib/CL/clCreateCommandBufferKHR.c
- lib/CL/clCreateCommandQueue.c
- lib/CL/clCreateContext.c
- lib/CL/clCreateContextFromType.c
- lib/CL/clCreateImage.c
- lib/CL/clCreateKernel.c
- lib/CL/clCreateProgramWithBinary.c
- lib/CL/clCreateProgramWithSource.c
- lib/CL/clCreateSampler.c
- lib/CL/clCreateSubBuffer.c
- lib/CL/clCreateSubDevices.c
- lib/CL/clGetDeviceIDs.c
- lib/CL/clGetExtensionFunctionAddressForPlatform.c
- lib/CL/clGetFunctionAddressForPlatformKHR.c
- lib/CL/clGetPlatformIDs.c
- lib/CL/clGetPlatformInfo.c
- lib/CL/clSetPlatformDispatchDataKHR.c
- lib/CL/devices/devices.c
- lib/CL/devices/devices.h
- lib/CL/pocl_cl.h
- lib/CL/pocl_icd.h
- lib/CL/pocl_intfn.h
- lib/CL/pocl_mem_management.c
- lib/CL/pocl_util.c
This implements the loader managed dispatch strategy presented here: https://github.com/KhronosGroup/OpenCL-Docs/issues/1003
> Implement cl_khr_icd 2.0.0 loader managed dispatch

- lib/CL/devices/remote/communication.c
- pocld/shared_cl_context.cc
It just replicated the arg 0's MD.
Didn't appear before getting to run more complex SPIR-V tests from chipStar.
> Fix for the PoCL-R SPIR-V arg MD detection

- CMakeLists.txt
- bin/poclcc.c
- config.h.in.cmake
- lib/CL/CMakeLists.txt
- lib/CL/devices/CMakeLists.txt
- lib/CL/devices/devices.c
- lib/CL/devices/proxy/libopencl_stub/CMakeLists.txt
- lib/CL/devices/proxy/libopencl_stub/libopencl.c
- lib/CL/devices/proxy/libopencl_stub/libopencl.h
- lib/CL/devices/proxy/libopencl_stub/rename_stub.h
- lib/CL/devices/proxy/pocl_proxy.c
- lib/CL/devices/pthread/pthread_scheduler.c
- lib/CL/pocl_cl.h
- lib/CL/pocl_networking.c
- pocl_opencl.h.in.cmake
- tests/runtime/test_pinned_buffers.cpp
- tests/runtime/test_svm.cpp
This pr does the following things:
* disables a couple of things not available on android
* renames the shared lib to libpocl.so when on android
* finds and adds logging library for android
* adds some explicit imports of libraries to pocl_networking.c that were not found otherwise
* updates some function declarations in the proxy driver
* adds a new cmake option called `PROXY_USE_LIBOPENCL_STUB` which allows the proxy device to link that instead of the system libopencl library.
* add a new cmake option called `RENAME_POCL` which does many things similar to what `ENABLE_PROXY_DEVICE` used to do.
* the proxy driver can now be used without renaming all of pocl's ocl functions by using `PROXY_USE_LIBOPENCL_STUB`
* fixes the ordering of a couple of includes on test files that would fail …
> add shared lib version of pocl for android

- doc/sphinx/source/android.rst
- doc/sphinx/source/features.rst
- doc/sphinx/source/proxy.rst
- doc/sphinx/source/remote.rst
additions:
* android topic
* update proxy docs with new features
* remove old remote build instructions for Android and point towards android page.
* also includes reference to original libopencl-stub project
> doc: add info on building PoCL on Android

- pocld/pocld.cc
The original code uses the ifa_addr member to get the address of an interface in the find_default_ip_address() function. However, for some interfaces, such as WireGuard, ifa_addr may be NULL. Therefore, it is necessary to check if ifa_addr is NULL, and if it is, skip the interface.
getifaddrs() man page: [https://man7.org/linux/man-pages/man3/getifaddrs.3.html]
> pocld: Fix pocld crash when running without listenning address

- .github/workflows/build_cmake.yml
- .github/workflows/build_cmake_macos.yml
Let's try to get this done before it *actually* becomes a problem.
Failing CI runs are caused by those machines having a too old version of github-runner.
> ci: bump 3rd party actions to get rid of deprecated nodejs dependency

- lib/CL/clCommandSVMMemcpyKHR.c
- lib/CL/clEnqueueSVMMemFill.c
- lib/CL/clEnqueueSVMMemcpy.c
Note: host2SVM, SVM2host and host2host are still unimplemented.
> Fix the SVM memcpy command buffering issues found by the CTS

- doc/sphinx/source/notes_6_0.rst
- lib/CL/clCreateCommandQueueWithProperties.c
- lib/CL/clGetPlatformInfo.c
Both extensions explicitly say that the hints provide no guarantee of anything, so a no-op implementation like this is fine. This simply makes PoCL not error out if an application actually tries to specify these hints.
> cl: Add no-op support for cl_khr_priority_hints and cl_khr_throttle_hints

- CMakeLists.txt
- doc/sphinx/source/notes_6_0.rst
- doc/sphinx/source/using.rst
- examples/boxadd/boxadd.c
- examples/matadd/matadd.c
- include/pocl.h
- lib/CL/clCreateProgramWithIL.c
- lib/CL/clGetDeviceInfo.c
- lib/CL/devices/common.c
- lib/CL/devices/common_utils.c
- lib/CL/devices/cpuinfo.c
- lib/CL/devices/devices.c
- lib/CL/devices/remote/remote.c
- lib/CL/pocl_cache.c
- lib/CL/pocl_cl.h
- lib/kernel/host/CMakeLists.txt
- lib/kernel/subgroups.c
- lib/kernel/work_group.c
- lib/kernel/work_group_alloca.h
- pocld/shared_cl_context.cc
- tests/regression/test_llvm_segfault_issue_889.c
- tests/workgroup/run_kernel.c
- tools/scripts/format-diff.sh
...via the binary-packaged oneAPI DPC++. Pls check the commits.
> Various features, fixes and hacks to make oneAPI-samples/Libraries/MPI/jacobian_solver SYCL run on PoCL-CPU and PoCL-R

- lib/CL/pocl_util.c
With multiple threads submitting commands to multiple devices there seems to be a race condition wrt the last migration event of a mem object. As a simple solution, just keep the object locked until the end of pocl_create_migration_commands.
> Make memobj locking more aggressive in create_migration_commands

- include/CL/cl_ext_pocl.h
- lib/CL/clGetMemObjectInfo.c
- lib/CL/clSetKernelArgDevicePointer.c
- tests/runtime/test_device_address.cpp
According to feedback from Karol in PR #1441:
- The address is now cl_ulong to avoid ambiguity and problems with the 32/64 bitness combination (this actually can be a realistic case with PoCL-R clients on very light weight devices).
- Dropped extra * from the address member.
> Updates to cl_ext_buffer_device_address

- doc/sphinx/source/using.rst
- examples/oneapi-samples/CMakeLists.txt
- examples/oneapi-samples/src/CMakeLists.txt
- examples/oneapi-samples/src/jacobian-solver/CMakeLists.txt
- examples/oneapi-samples/src/jacobian-solver/README.md
- examples/oneapi-samples/src/jacobian-solver/src/jacobian_gpu_openmp_multidevice.cpp
- examples/oneapi-samples/src/jacobian-solver/src/jacobian_gpu_sycl_multidevice.cpp
- lib/CL/devices/basic/basic.c
- lib/CL/pocl_build.c
- lib/llvmopencl/SVMOffset.cc
Can now run a multi-device SYCL variation of the jacobian solver over PoCL-R.
Also add env POCL_IGNORE_CL_STD (for OpenMP offload via ipcx).
> PoCL-R SVM offsetting improvements

- lib/CL/clEnqueueMemFillINTEL.c
- lib/CL/clGetDeviceInfo.c
- lib/CL/clGetMemAllocInfoINTEL.c
- lib/CL/clMemAllocINTEL.c
- lib/CL/devices/basic/basic.c
- lib/CL/devices/common_driver.h
- lib/CL/devices/cuda/pocl-cuda.c
- lib/CL/devices/level0/level0-driver.cc
- lib/CL/devices/level0/pocl-level0.cc
- lib/CL/devices/prototypes.inc
- lib/CL/devices/remote/remote.c
- lib/CL/pocl_cl.h
- lib/CL/pocl_llvm_wg.cc
- lib/CL/pocl_util.c
- lib/CL/pocl_util.h
- pocld/shared_cl_context.cc
Moved more of the USM handling to the API layer, enabled by
the common raw pointer book keeping functionality.
Fix clEnqueueMemFillINTEL() for the new shadow buffering scheme.
Advertise USM from Remote in case SVM enabled.
> USM refactoring and fixes

- lib/CL/devices/cuda/pocl-cuda.c
- lib/CL/pocl_util.c
- lib/CL/pocl_util.h
- tests/runtime/CMakeLists.txt
Enabled runtime/test_device_address as it passed on RTX 3060 at least.
> CUDA: advertise cl_ext_buffer_device_address

- CMakeLists.txt
- tools/scripts/devel-envs.sh
Add trailing `/` into OCL_ICD_VENDORS so POCL gets recognized by OpenCL ICD Loader versions prior
https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/91.
> Add trailing `/` into OCL_ICD_VENDORS

- lib/CL/pocl_llvm_utils.cc
Fix pocl_llvm_utils.cc::parseModuleIRMem() triggered the assertion on the title when parseBitcodeFile() call returned an error. The Expected object was checked but its stored Error object was not and that triggered the assertion. In this patch the error gets checked by passing it to toString().
> Fix "Expected<T> must be checked before access or destruction."

- lib/CL/devices/cuda/pocl-cuda.c
Relax the limit from 1/4 * CL_DEVICE_GLOBAL_MEM_SIZE to currently available free memory reported by cuMemGetInfo() at device initialization time.
Motivation: enable a HeCBench case, running on chipStar/OpenCL->PoCL/CUDA->RTX3060, to allocate ~4GiB buffers.
Edit: was: Relax the limit from 1/4 to 1/2 * CL_DEVICE_GLOBAL_MEM_SIZE.
> CUDA: relax CL_DEVICE_MAX_MEM_ALLOC_SIZE limit

- CMakeLists.txt
- doc/sphinx/source/notes_6_0.rst
- lib/CL/devices/cuda/pocl-cuda.c
- lib/CL/devices/cuda/pocl-ptx-gen.cc
- lib/CL/devices/cuda/pocl-ptx-gen.h
- lib/CL/pocl_util.c
- lib/CL/pocl_util.h
- lib/kernel/cuda/CMakeLists.txt
- lib/kernel/cuda/subgroup.ll
- lib/kernel/cuda/subgroup_ballot.cl
- lib/kernel/cuda/subgroup_shuffle.cl
Add support for subgroup ballot and shuffles for SM >=8.0 architectures. Kernel code generation failed prior this patch due to high SM version because:
* LLVM disables instruction selection for certain intrinsics when targeted SM and PTX versions are high enough.
* PTX assembler removes support for some instructions (e.g. non-sync variants of ballot and shfls) after a certain PTX version.
The operations are attempted to be supported by lowering SM and PTX versions for the codegen when possible.
Other changes:
* Advertise `cl_khr_subgroup_ballot` for CUDA device when capable. However, only `sub_group_ballot()` is implemented now. This enables a HeCBench case on chipStar/PoCL-CUDA/sm_86.
* ~~Advertise `cl_khr_subgroup_shuffle` and `cl_khr_subgroup_shuffle_relative` for CUDA device when …
> CUDA: Support subgroup ballot & shuffles for recent SM archs and others

- lib/CL/pocl_util.c
Fixes possible deadlock where `pocl_create_migration_commands()` and `pocl_free_event_memobjs()` may try to acquire the same memory object lock. Occurs in `example1` when compiled with
```
cmake -DENABLE_ALMAIF_DEVICE=ON -DENABLE_POCL_BUILDING=ON ..
```
> Move command enqueues out of critical section

- lib/CL/devices/common.c
- lib/CL/devices/common_utils.c
- lib/CL/devices/common_utils.h
- lib/CL/devices/pthread/pthread_scheduler.c
- lib/CL/devices/tbb/tbb_scheduler.cc
- lib/CL/pocl_llvm_utils.cc
i386 distro builds are still broken in 5.0 since there were some related non-conflicting changes between I submitted the patch and it got applied
these two patches have been part of the Debian packages for 5.0 since the beginning, I just lost track of submitting them
there are some new exported symbols lacking the pocl_ prefix, add it
> fixes for 6.0

- lib/CL/clGetEventInfo.c
- lib/CL/clGetEventProfilingInfo.c
According to https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/clGetEventInfo.html and https://registry.khronos.org/OpenCL/sdk/1.0/docs/man/xhtml/clGetEventProfilingInfo.html, the returned value should be CL_INVALID_EVENT if the event is not a valid object.
> Fix return err value in clGetEvent(Profiling)Info

- CMakeLists.txt
- include/_clang_opencl.h
- lib/kernel/subgroups.cl
- lib/llvmopencl/LLVMUtils.cc
With these tiny-llama-1b-chat/INT4_compressed_weights runs via OpenVINO on PoCL-CPU, but segfaults due to an indexing error.
> cl_intel_subgroups_char and removal of an illegal assertion

- lib/CL/clReleaseCommandBufferKHR.c
- lib/CL/devices/proxy/pocl_proxy.c
On FreeBSD, `alloca` comes from `stdlib.h`: https://man.freebsd.org/cgi/man.cgi?alloca (vs. Linux: https://man7.org/linux/man-pages/man3/alloca.3.html).
> Fix compilation on FreeBSD.

- README.md
- include/_clang_opencl.h
- lib/CL/pocl_cl.h
- lib/CL/pocl_llvm_build.cc
Small patches to make OpenVINO run the tiny-llama-1b-chat model infer. via the L0 driver.
An example run:
```
samples/cpp/multinomial_causal_lm/multinomial_causal_lm ~/src/openvinino_notebooks/notebooks/llm-chatbot/tiny-llama-1b-chat/INT4_compressed_weights/ "Why is the Sun yellow?"
PoCL Level0
6 warnings generated.
12 warnings generated.
The answer, as you would expect, is because sunlight contains an abundance of atoms of iron (Fe), a naturally occurring element that is red-coloured because of the presence of one of its elements.
12. Why are there stars with blue-grey hues? Blue-grey colours are produced by iron-rich regions of the Sun, which contain large numbers of elements like nickel (Ni), cobalt (Co), and magnesium
```
> Fixes to make OpenVINO run on the L0 driver

- lib/CL/devices/remote/remote.c
pocl_remote_init() returned CL_INVALID_DEVICE, which was then being returned by clGetDeviceIDs(). As per the specs clGetDeviceIDs() doesn't return CL_INVALID_DEVICE. In this commit, it is changed to CL_DEVICE_NOT_FOUND as that was the most appropriate error that clGetDeviceIDs() can return for some failure in initializing a device in the remote driver.
> remote fix returned error codes at init for clGetDeviceIDs

- include/messages.h
- lib/CL/clGetDeviceInfo.c
- lib/CL/devices/remote/communication.c
- lib/CL/devices/remote/communication.h
- lib/CL/devices/remote/remote.c
- pocld/shared_cl_context.cc
- pocld/shared_cl_context.hh
- pocld/virtual_cl_context.cc
* Pass (vendor-specific) device infos as raw data from the device to the host to implement.
* Implement host_unified_memory and max_num_sub_groups device queries.
> PoCL-R: Support for more (vendor-specific) device infos

- doc/sphinx/source/using.rst
- lib/CL/clCreateProgramWithIL.c
- lib/CL/devices/common.c
- lib/CL/devices/common_driver.c
- lib/CL/devices/hsa/pocl-hsa.c
- lib/CL/devices/level0/pocl-level0.cc
- lib/CL/devices/vulkan/pocl-vulkan.c
- lib/CL/pocl_llvm_build.cc
- lib/CL/pocl_llvm_wg.cc
- lib/CL/pocl_runtime_config.c
- lib/CL/pocl_runtime_config.h
- lib/CL/pocl_util.c
- lib/CL/pocl_util.h
- pocld/shared_cl_context.cc
I'm working on distributing pocl for use with the Julia programming language. One of the issues I ran into, is that pocl embeds hard-coded paths to binaries like `llvm-spirv` and `clang` in the binary with values set at configuration time. That doesn't work for our use case, where the compile-time paths in our build container doesn't match the run-time situation (which may differ from user to user, as Julia installs binary artifacts in `~/.julia/artifacts`).
In this PR, I propose adding the ability to override paths to executables through `POCL_XXX` environment variables. At initialization time, our pocl wrapper package populates those variables with paths to wrapper scripts that point to our binaries (in addition with some set-up for library paths).
> Allow overriding paths to executables using env vars.

- lib/CL/devices/remote/remote.c
- pocld/daemon.cc
- pocld/shared_cl_context.cc
Building on arch linux had the unfortunate
issue of not finding std::find and std::for_each
unless explicitly importing algorithm.
There was also a case of a size and null pointer
being swapped which caused a casting error.
> poclr: fix build on arch linux

- include/CMakeLists.txt
This removes last reference to  _libclang_versions_checks.h (in CMakeLists.txt), which was removed in [2ec5e820a9b5d58fb770cf9a3dc1795ca1a418d4](https://github.com/pocl/pocl/commit/2ec5e820a9b5d58fb770cf9a3dc1795ca1a418d4). 
This did not affect compilation but installation failed: 
```
CMake Error at include/cmake_install.cmake:54 (file):
file INSTALL cannot find
"pocl/include/_libclang_versions_checks.h":
No such file or directory.
```
> Remove nonexisting reference to _libclang_versions_checks.h in CMakeLists.txt

- lib/CL/devices/proxy/pocl_proxy.c
- tests/runtime/test_queue_creation_with_hints.c
Do note that i've only tested this on x86 with example0 and not yet on android
This commit updates the proxy device to get
its mem_objs from the node instead of the event,
as is now done in all other devices.
There is also a fix in one of the tests for
when pocl is renamed.
> proxy: update to new organization of mem_objs

- lib/llvmopencl/Kernel.cc
- lib/llvmopencl/ParallelRegion.cc
This is to facilitate more efficient index analysis for loop vectorizers.
> Loopvec: Place global id loads as close to the user as possible

- lib/CL/pocl_util.c
Running under LLDB seems to cause `waitpid` to return `EINTR`:
```
pocl: waitpid() failed.
Process 18432 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
frame #0: 0x000000019205e600 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x19205e600 <+8>:  b.lo   0x19205e620    ; <+40>
0x19205e604 <+12>: pacibsp
0x19205e608 <+16>: stp    x29, x30, [sp, #-0x10]!
0x19205e60c <+20>: mov    x29, sp
Target 0: (julia) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
* frame #0: 0x000000019205e600 libsystem_kernel.dylib`__pthread_kill + 8
frame #1: 0x0000000192096f70 libsystem_pthread.dylib`pthread_kill + 288
frame #2: 0x0000000191fa3908 libsystem_c.dylib`abort + 128
frame #3: …
```
> Retry waitpid in case of EINTR for debugger compatibility.

- CMakeLists.txt
Otherwise we get plenty of warnings because of the `visibility(default)` from `POCL_EXPORT` applied to `cl.h`'s typedefs.
> Set no-ignored-attributes when compiling with Apple's Clang.

- lib/llvmopencl/ParallelRegion.cc
- lib/llvmopencl/ParallelRegion.h
- lib/llvmopencl/SubCFGFormation.cc
- lib/llvmopencl/WorkitemHandler.cc
- lib/llvmopencl/WorkitemHandler.h
- lib/llvmopencl/WorkitemLoops.cc
- tests/workgroup/loopbarriers.cl
Implement subgroups for also CBS
With this change, the following subgroup CTS tests pass:
```
POCL_WORK_GROUP_METHOD=cbs ctest -R subgr
Test project /home/pjaaskel/src/pocl/build-cpu
Start 407: conformance_main_subgroups
1/4 Test #407: conformance_main_subgroups ..........   Passed   34.34 sec
Start 569: conformance_spirv_subgroups
2/4 Test #569: conformance_spirv_subgroups .........   Passed    8.47 sec
Start 579: conformance_main_subgroups_micro
3/4 Test #579: conformance_main_subgroups_micro ....   Passed    4.58 sec
Start 749: conformance_spirv_subgroups_micro
4/4 Test #749: conformance_spirv_subgroups_micro ...   Passed    1.91 sec
100% tests passed, 0 tests failed out of 4
```
It used to be implemented only for 'loopvec' and 'loops'.
Also the PR adds a better workaround for the …
> Subgroups support for CBS

- CMakeLists.txt
- lib/CL/devices/CMakeLists.txt
- lib/CL/devices/cpu_dbk/CMakeLists.txt
- tests/runtime/CMakeLists.txt
... due to different package name (libturbojpeg).
Also, run the `test_dbk_jpeg` test.
> Fix couldn't find libjpeg-turbo package built from sources

- tests/runtime/CMakeLists.txt
Fix overwrote previous OCL_30_TESTS variable.
> Fixup for #1605

- lib/CL/pocl_cl_half_util.c
- poclu/CMakeLists.txt
- poclu/misc.c
- poclu/poclu.h
- tests/tce/fp16/host.cpp
@franz I thought about about using the `cl_half.h` library for pocl's internal functions, but it was not clear to me how the current implementation handles an under-/over-flow errors. Do you have any opinions?
`cl_half.h` provides these options:
```
typedef enum
{
CL_HALF_RTE, // round to nearest even
CL_HALF_RTZ, // round towards zero
CL_HALF_RTP, // round towards positive infinity
CL_HALF_RTN, // round towards negative infinity
} cl_half_rounding_mode;
```
> remove cl_half utils from poclu

- .github/workflows/build_linux.yml
Let's keep them at least somewhat in sync with the main workflows to rule out unrelated causes of errors.
> ci: bump remote and RDMA to LLVM 18

- doc/sphinx/source/using.rst
- lib/CL/pocl_llvm_build.cc
Another env var customization to make pocl portable. Otherwise we run into compilation failures on systems that don't have a system-wide linker:
```
From worker 3:	error: unable to execute command: Executable "ld" doesn't exist!
From worker 3:	error: linker command failed with exit code 1 (use -v to see invocation)
From worker 3:	Final linking of kernel sum failed.
```
We aim to use this in Julia by redistributing a copy of lld (automatically downloaded in the user's home folder) and using that binary instead.
> Make it possible to configure the linker path used by Clang.

- CMakeLists.txt
Currently Khronos ICD version is not checked but last releases already support OpenCL 3.0
> Support Khronos ICD if the version >= 3.0

- doc/sphinx/source/using.rst
- lib/CL/pocl_llvm_build.cc
- lib/CL/pocl_runtime_config.c
- lib/CL/pocl_runtime_config.h
Implements https://github.com/pocl/pocl/pull/1621#issuecomment-2421560334.
Semicolon-separated for now, without dealing with escaping. I considered using more obscure characters as a separator, but that may be problematic on platforms like Windows.
> Replace POCL_PATH_LD by a more generic semicolon-separated POCL_ARGS_CLANG.

- lib/kernel/host/CMakeLists.txt
- lib/kernel/isinf_half.cl
- tests/kernel/CMakeLists.txt
- tests/kernel/test_halfs.cl
They were missing because `isinf()` definitions were pulled from `lib/kernel/libclc*` which doesn't have overloads for `half` scalar and vectors.
Resolves #1562.
> CPU: Fix missing isinf(half) and isinf(halfn)

- lib/kernel/subgroups.c
- lib/kernel/work_group.c
Remove the C standard includes which are not guaranteed to be provided under -ffreestanding. Replace `INFINITY` with `__builtin_inf()`.
Fixes a compilation issue on MSVC toolchain.
> Remove C standard includes in kernel builtin sources

- lib/CL/devices/printf_base.h
Fixes compilation on MSVC (does not recognize `__builtin_*` functions).
> Replace __builtin_{inf,nan} with INFINITY and NAN from math.h

- CMakeLists.txt
- examples/EinsteinToolkit/EinsteinToolkit.c
- lib/CL/clCreateCommandBufferKHR.c
- lib/CL/clEnqueueCommandBufferKHR.c
- lib/CL/devices/cuda/pocl-cuda.c
- lib/CL/devices/pthread/pthread_scheduler.c
- lib/CL/devices/remote/communication.c
- lib/CL/devices/remote/remote.c
- lib/CL/devices/tbb/tbb_scheduler.cc
- lib/CL/devices/vulkan/pocl-vulkan.c
- lib/CL/pocl_cq_profiling.c
- lib/llvmopencl/Workgroup.cc
- tests/runtime/test_clCreateSubDevices.c
- tests/runtime/test_clGetEventInfo.c
- tests/runtime/test_command_buffer.c
- tests/runtime/test_command_buffer_images.c
- tests/runtime/test_command_buffer_multi_device.c
- tests/spirv/printf.cc
- tests/workgroup/run_kernel.c
Ban VLAs because MSVC does not support them - not even for C code because C99 is not supported where the VLA is a mandatory feature. This restriction is attempted to be enforced with -Werror=vla.
VLAs are replaced with malloc, std::vector or alloca.
> Ban variable length arrays

- CMakeLists.txt
- config.h.in.cmake
- lib/CL/devices/common.c
- lib/CL/devices/common_utils.c
- lib/CL/devices/cuda/pocl-cuda.c
- lib/CL/devices/prototypes.inc
- lib/CL/pocl_cl.h
- lib/CL/pocl_llvm.h
- lib/CL/pocl_llvm_build.cc
- lib/CL/pocl_llvm_wg.cc
- lib/CL/pocl_util.c
- lib/CL/pocl_util.h
- lib/kernel/pocl_run_all_wgs.c
- lib/llvmopencl/DebugHelpers.h
- lib/llvmopencl/Flatten.cc
- lib/llvmopencl/Workgroup.cc
- lib/llvmopencl/linker.cpp
* Enable including a device-main in the bitcode library. Device mains can have the kernel command handling and launch the work-groups via grid launcher.
* Fix grid launcher generation. It rots because phsa is not tested anymore, but is useful for some targets.
* Allow overriding the final linkage step via a new finalize_binary() hook.
* Cleanups, documentation, minor internal convenience. pocl_init_default_device_infos() now lets setting triplet etc. beforehand and it doesn't overwrite with the 'host' defaults. This enables generating the built-in lib pathnames with the helper with more flexibility.
> Grid launcher, a new bin finalization hook, cleanups

- lib/llvmopencl/Workgroup.cc
Needed for loading the symbols on Windows/MSVC.
> MSVC: Attach dllexport attribute to WG functions

- lib/CL/pocl_builtin_kernels.c
This should clear up a lot of the CI warnings.
Also inits some pointers to NULL and sets
builtin_kernel_attrs to NULL.
> misc: fix missing braces around initializer warning

- lib/CL/devices/pthread/pthread.c
- lib/CL/devices/pthread/pthread_scheduler.c
* Replace `pthread_exit(NULL)` with `return NULL`.
* Remove unused includes.
> pthread: clean-ups for MSVC toolchain

- bin/poclcc.c
- doc/sphinx/source/pocl_binary.rst
- examples/accel/OpenCLcontext.cpp
- examples/scalarwave/scalarwave.c
- poclu/misc.c
- poclu/poclu.h
- tests/runtime/test_dbk_jpeg.c
- tests/runtime/test_kernel_cache_includes.c
* Fix writing a binary to a file in *text mode* garbled the contents due to special handling of some characters on Windows.
* Fix kernel sources got truncated due to `ftell()` returning a value that does not match to the actual file size (on Windows) if the file is opened in text mode ("If the stream is open in text mode, the value returned by this function is unspecified and is only meaningful as the input to fseek()").
* Fix documentation sugggested use of `ftell()` on a file opened in text mode.
> Fix few file handling issues

- lib/CL/CMakeLists.txt
- lib/CL/devices/common.c
- lib/CL/pocl_ipc_mutex.h
- lib/CL/pocl_ipc_mutex_win.cc
... to avoid race condition on `pocl_rename()` calls by multiple processes and threads targeting same files. File renaming and moving does not seems to be atomic operation on windows as `pocl_rename()` calls within the `llvm_codegen()` occationally fail while running internal tests parallel with kernel cache cleared.
Add an API for name interprocess mutex and implement it for Windows. Use it avoid the race condition.
> Use interprocess mutex for llvm_codegen() on Windows

- lib/CL/pocl_llvm_metadata.cc
It caused build failure on MSVC toolchain.
> Remove unused pthread include

- examples/example1/example1.c
- lib/CL/clEnqueueUnmapMemObject.c
- lib/CL/devices/cpu_dbk/pocl_dbk_khr_onnxrt_cpu.c
- lib/CL/devices/printf_base.c
- lib/CL/devices/printf_buffer.c
- lib/CL/devices/remote/remote.c
- lib/CL/pocl_binary.c
- lib/CL/pocl_builtin_kernels.c
- lib/CL/pocl_compiler_macros.h
- lib/CL/pocl_tensor_util.c
- tests/runtime/test_dbk_jpeg.c
- tests/runtime/test_event_free.c
- tests/runtime/test_fill-buffer.c
A WIP fixing warnings that `-Wall -Wextra` show so that in the future it would be possible to compile locally and see warnings introduced by new code.
As a side note, the CI could probably also use the `-Wno-unused-function` flag.
Some things being fixed:
* signed compare warnings
* set but unused variables
* bracket warnings
> misc: fix warnings with -Wall and -Wextra

- tools/scripts/format-branch.sh
- tools/scripts/format-diff.sh
- tools/scripts/format-last-commit.sh
* Try use the latest `clang-format-XX` in the PATH first.
format-branch.sh failed with following error:
```
/mnt/md1/linehill/ws-pocl-2/pocl/tools/scripts/style.GNU:25:3: error: unknown enumerated scalar
Enabled:         false
^
Error reading /mnt/md1/linehill/ws-pocl-2/pocl/tools/scripts/style.GNU: Invalid argument
Formatting pocld/shared_cl_context.cc
/mnt/md1/linehill/ws-pocl-2/pocl/tools/scripts/style.CPP:26:3: error: unknown enumerated scalar
Enabled:         false
^
Error reading /mnt/md1/linehill/ws-pocl-2/pocl/tools/scripts/style.CPP: Invalid argument
```
Perhaps, due to the `clang-format` (v14) on my system being too old for the custom style files. There are other formatters in `clang-format-XX` form in the PATH and using the lates one (`clang-format-19`) fixes the issue. Change …
> Improve formatter scripts

- lib/CL/devices/remote/communication.c
for large files, use the slow queue as the fast
queue can't handle large amounts of data (like onnx blobs).
> remote: make the remote faster by going slower

- examples/measure_overhead/measure_migration_overhead.cc
- lib/CL/devices/printf_base.c
- pocld/CMakeLists.txt
- pocld/connection.cc
- pocld/peer.cc
- pocld/peer_handler.cc
- pocld/reply_th.cc
- pocld/request.cc
- tests/regression/test_issue_757.cpp
- tests/runtime/test_subbuffers.cpp
types of fixes include:
* sign compare fixes
* using range operators in for loops
* init clearifications
* warnings related to use of move
* removing const from return types
note: this does not address all warnings
> misc: cpp related CI warning fixes

- lib/CL/devices/basic/basic.c
- lib/CL/devices/common_utils.c
- lib/CL/devices/cpu_dbk/pocl_dbk_khr_onnxrt_cpu.c
- lib/CL/devices/cpu_dbk/pocl_dbk_khr_onnxrt_cpu.h
- tests/runtime/test_dbk_onnx_inference.c
This commit fixes names that were missed with
the refactor to match the dbk spec.
@linehill I noticed there is now the `CL_TENSOR_DTYPE_FP8E4M3_EXP` data type, and I mapped that to onnx's [FP8E4M3FN](https://onnx.ai/onnx/technical/float8.html), which does not represent infinite values. Could this be a problem? Intel's [FP8-emulation-toolkit](https://github.com/IntelLabs/FP8-Emulation-Toolkit) doesn't either so I was wondering if it is the same case here.
> dbk: rename onnxrt types

- cmake/LLVM.cmake
- lib/CL/clGetDeviceInfo.c
- lib/CL/devices/almaif/openasip/AlmaifCompileOpenasip.cc
- lib/CL/devices/basic/basic.c
- lib/CL/devices/common.c
- lib/CL/devices/common_driver.c
- lib/CL/devices/common_driver.h
- lib/CL/devices/tce/tce_common.cc
- lib/CL/devices/tce/tce_common.h
- lib/CL/pocl_llvm_build.cc
- lib/CL/pocl_mem_management.c
- lib/llvmopencl/Workgroup.cc
- tests/regression/test_autolocals_in_constexprs.cpp
- tests/regression/test_barrier_between_for_loops.cpp
- tests/regression/test_issue_757.cpp
- tests/regression/test_locals.cpp
- tests/regression/test_structs_as_args.cpp
- tests/regression/test_workitem_func_outside_kernel.cpp
- tests/runtime/CMakeLists.txt
- tests/runtime/test_subbuffers.cpp
- tests/workgroup/for_with_divergent_return.cl
- tools/scripts/run_cpu_tests
* Reduce the iteration count in for_with_divergent_return test
* Refactor copy (rect) default implementations: Split to a *memcpy version which takes in a target pointer so it can be called from drivers with a host backing device store pointer or similar use case.
* tests/kernel/common.cl: enable int64 tests only if cl_khr_int64
* argbuffer wrapper: Always align args to MAX_EXTENDED_ALIGNMENT to make passing structs on argbuffer feasible.
* cmake/LLVM: Allow overriding the LLVM_HOST_TARGET
* Remove test_subbuffers_multidevice: The test runner scripts should setup the device list and run test_subbuffers which tests all available devices.
* Fix the broken run_cpu_tests script
> Yet more misc. fixes

- cmake/LLVM.cmake
- config.h.in.cmake
- lib/CL/devices/common.c
- lib/CL/pocl_llvm_build.cc
- lib/CL/pocl_llvm_wg.cc
- pocld/shared_cl_context.cc
clang/include/clang/Basic/AttributeCommonInfo.h now has this
`enum class Scope { NONE, CLANG, GNU, MSVC, OMP, HLSL, GSL, RISCV };`
which conflicts with the config.h generated
`#define CLANG "@CLANG@"`.
This renames `CLANG` to `CLANGCC`.
It teaches LLVM.cmake to allow and detect llvm 20 as well.
Link: https://gerrit.kalray.eu/id/Ifb026be79d50537531e3013c6e6356434616ac5a
> Initial LLVM20 support

- lib/CL/devices/common_driver.c
- lib/CL/devices/common_utils.c
- lib/CL/pocl_mem_management.c
- lib/CL/pocl_util.c
- lib/llvmopencl/Workgroup.cc
This commit removes functions not needed anymore
and puts debugging functions behind ifdefs.
> misc: remove unused function warnings

- CMakeLists.txt
- lib/CL/devices/CMakeLists.txt
- lib/CL/devices/proxy/CMakeLists.txt
- lib/CL/pocl_networking.c
Some changes to fix building the android reference app with latest pocl main.
When PROXY_USE_LIBOPENCL_STUB is enabled then the libopen_stub included in the proxy device is used and we do not need to link to libopencl.
> build fixes for android reference app

- .github/workflows/build_full_cts.yml
- CMakeLists.txt
- bin/CMakeLists.txt
- bin/spirv_fix_atomic_compare_exchange.cc
- cl_offline_compiler.sh.in.cmake
- lib/CL/devices/common_utils.c
- lib/CL/devices/spirv_parser.cc
- lib/CL/devices/spirv_parser.hh
- lib/kernel/SPIR/generate_spir_wrapper.py
- tools/scripts/run_level0_tests
Fixes all remaining OpenCL-CTS SPIR-V tests. Howewer, had to disable program-scope variables (for ENABLE_CONFORMANCE=ON).
> SPIR-V fixes

- lib/CL/pocl_llvm_build.cc
The CompilerInstance file system is never set, so it is nullptr and deferrecing it with `getVirtualFileSystem` would crash.
This uses `llvm::vfs::getRealFileSystem` to obtain the current process's working directory.
> [LLVM20] Create a physical file system for the diagnostics

- CMakeLists.txt
- bin/CMakeLists.txt
cl_offline_compiler.sh.in.cmake includes the target 'spirv_fix_atomic_compare_exchange', which is not added if ENABLE_POCLCC=0.
I am not sure if this is the correct fix for this.
> Build fix with ENABLE_POCLCC=0

- .github/workflows/build_linux_gh.yml
- CMakeLists.txt
- doc/sphinx/source/dbk.rst
- lib/CL/devices/cpu_dbk/pocl_dbk_khr_onnxrt_cpu.c
The version requirements for onnxruntime and libxsmm in CMakeLists.txt were wrong. Additionally ubuntu 24.04 finally packages libxsmm and that version was accepted by the build scripts... but then fails at build time with little indication of what the problem actually is. This should help avoid losing much time to confusion in the future.
@franz if you have libxsmm set up on CI somewhere this probably breaks since upstream still declares its version as 0.17.0 (latest release tag) even for git builds.
> Be a bit more explicit about DBK build dependencies

- examples/conformance/CMakeLists.txt
- lib/CL/devices/level0/level0-driver.cc
Adds workarounds for issues encountered when running OpenCL-CTS.
* FP16 has been disabled in conformance mode for now, this needs a fix in the GPU drivers.
* `test_api` fails the `get_kernel_arg_info` test, because it incorrectly calculates argument sizes. Fixed in our CTS fork, workarounded in PoCL (upstreaming takes a while)
> OpenCL-CTS / LevelZero

- lib/CL/devices/remote/communication.c
- pocld/connection.cc
In the case of an interrupt, try reading the data
again. This may not be the most considerate thing
to do, but it will read th data.
I encountered this case on Android where establishing the connection can take a while.
> remote: handle EINTR error

- lib/llvmopencl/Barrier.h
- lib/llvmopencl/BarrierTailReplication.cc
- lib/llvmopencl/DebugHelpers.h
- lib/llvmopencl/ImplicitConditionalBarriers.cc
- lib/llvmopencl/Kernel.cc
- lib/llvmopencl/LLVMUtils.cc
- lib/llvmopencl/LoopBarriers.cc
- lib/llvmopencl/WorkitemHandler.cc
- lib/llvmopencl/WorkitemLoops.cc
- tests/workgroup/CMakeLists.txt
- tests/workgroup/for_with_divergent_return.cl
Also dropped the crazy INT_MAX iteration count in for_divergent_return.cl to 100 to reduce the runtime of the test case without affecting the tested aspect.
> Cleanups [NFC]

- include/pocl.h
- lib/CL/devices/level0/level0-compilation.cc
- lib/CL/devices/level0/level0-driver.cc
- lib/CL/devices/level0/level0-driver.hh
- lib/CL/devices/level0/pocl-level0.cc
- lib/CL/pocl_llvm.h
- lib/CL/pocl_llvm_wg.cc
- tests/kernel/CMakeLists.txt
- tests/kernel/test_ptr_compare.cl
Fix PoCL/level0 generated SPIR-V from OpenCL C with a version not supported by the driver and crashed in the presence of an instruction the version enabled (OpPtrEqual).
> Fix unsupported SPIR-V was generated from OpenCL C

- lib/CL/clGetMemAllocInfoINTEL.c
When passed an SVM pointer, clGetMemAllocInfoINTEL should return UNKNOWN as the USM type, and default placeholder values for other queries.
This is needed to differentiate between SVM pointers, which should be freed using clSVMFree, and USM pointers, which should be freed using clMemFreeINTEL or clMemBlockingFreeINTEL.
> fix clGetMemAllocInfoINTEL queries for SVM pointers

- include/pocl.h
Otherwise the major/minor field references can conflict with macro definitions pulled from `sys/sysmacros.h`:
```
[13:10:48] /workspace/srcdir/include/pocl.h: In constructor ‘pocl_version_t::pocl_version_t()’:
[13:10:48] /workspace/srcdir/include/pocl.h:585:23: error: class ‘pocl_version_t’ does not have any field named ‘gnu_dev_major’
[13:10:48]   585 |   pocl_version_t () : major (0), minor (0) {}
[13:10:48]       |                       ^~~~~
```
x-ref https://stackoverflow.com/a/33681284
> Initialize pocl_version_t members using braces.

- lib/llvmopencl/KernelCompilerUtils.h
- lib/llvmopencl/LLVMUtils.cc
- lib/llvmopencl/WorkitemHandler.cc
- lib/llvmopencl/WorkitemHandler.h
- lib/llvmopencl/linker.cpp
* Convert the built-ins to declarations after first linking them in to handle all cases similarly.  Previously, if a built-in called an ID built-in, it was linked in as a defined one and the logic of excluding them didn't work.
* Also add get_num_groups() to the expanded built-ins to avoid yet one more source of messy switch..cases.
> Better logic for the ID built-in expansion decision

- lib/CL/devices/cuda/CMakeLists.txt
Fixes failing test:
```text
4/251 Test   #5: pocl_test_dlopen_device_cuda ..........................................................***Failed    0.16 sec
dlopen($ORIGIN/../../lib/CL/devices/cuda/libpocl-devices-cuda.so, RTLD_NOW) failed: /build/pocl/src/pocl/build/tests/runtime/../../lib/CL/devices/cuda/libpocl-devices-cuda.so: undefined symbol: cudaFree
```
Tested with `clinfo`.
> link cudart

- CMakeLists.txt
* Add entry for PoCL in (64-bit) Windows registry for Khronos ICD loader.
* Offer to uninstall the previous PoCL installation (of any version installed anywhere). Otherwise, this acts as a notification about already installed PoCL.
> NSIS installer: ICD registration, uninstall previous PoCL

- lib/CL/CMakeLists.txt
- lib/CL/pocl_cache.c
Fixes "pocl-level0.cc.obj : error LNK2019: unresolved external symbol __imp_pocl_cache_...".
> MSVC: a fix for ENABLE_LOADABLE_DRIVERS=ON ENABLE_LEVEL0=ON

- lib/CL/devices/common.c
I tested this with the CPU runtime using clang 19, and it works.
clInfo announces the new SPIR-V versions, and I can query them with `clGetDeviceInfo` and `CL_DEVICE_IL_VERSION`.
However, `ILs with version`  only reports version 1.0 to 1.5. I don't really understand why. As far as I understand, the list is created here: https://github.com/pocl/pocl/blob/a4799460ffb0cd45d16a894bfe653acb5b6d28f2/lib/CL/devices/common.c#L2011
I don't fully digged into the code, but not clear to me why it would not list 1.6.
> Extend general SPIR-V support to 1.6

- lib/CL/devices/common.c
This brings in the subgroup ballot support which chipStar can use.
This exposes an issue in TestBallot (at least for me):
```
/home/pjaaskel/src/chipStar/build-llvm-19/tests/runtime/TestBallot
TestBallot: /home/pjaaskel/src/chipStar/llvm-project/llvm/lib/Transforms/Utils/ValueMapper.cpp:978: void {anonymous}::Mapper::remapInstruction(llvm::Instruction*): Assertion `(Flags & RF_IgnoreMissingLocals) && "Referenced value not in value map!"' failed.
...
(gdb) call I
$1 = (llvm::Instruction *) 0x55556656e5f0
(gdb) call I->dump()
%22 = load i64, ptr %_local_size_x, align 8
```
Let's see if the CI also fails.
> Enable SPIR-V 1.3 with LLVM v19

- lib/CL/pocl_llvm_spirv.cc
Fixes the compilation error seen in https://github.com/pocl/pocl/pull/1769#issuecomment-2704181719
The current long-term support release of Julia is build against LLVM 15.
> Fix compilation with LLVM 15

- lib/CL/pocl_llvm_build.cc
This occurred because of `const char *` being used as a key in the `UnbundledHeaders` map resulting in pointer comparison instead of string comparison. The error itself was caused by string literals with same contents but different pointer - one used for adding an entry and the other used for lookup.
> Fix `Expression: It != UnbundledHeaders.end()` error

- include/pocl.h
- lib/CL/devices/devices.c
- lib/CL/pocl_util.c
* Fix `pocl_dynlib_pathname()` failed. Or rather `GetModuleHandleEx()` call failed because an `address` argument was pointing to a function that was not exported properly (its definition lacked `POCL_EXPORT`).
* Fix failure to find builtin OpenCL C headers on `ENABLE_HEADER_BUNDLING=OFF` configuration. This occurred because
`pocl_get_private_datadir()` returned incorrect path.
> Windows: Fix ENABLE_RELOCATION=ON issues

- lib/llvmopencl/Workgroup.cc
This should at speed up at least codegen and dlopen() somewhat as it typically splits the LLVM Module size to about half.
> WG: Remove the original kernel if not needed any longer

- lib/CL/clSetKernelExecInfo.c
- lib/CL/devices/basic/basic.c
- lib/CL/devices/remote/remote.c
- lib/CL/pocl_mem_management.c
- lib/CL/pocl_mem_management.h
- lib/CL/pocl_util.c
Setting of the indirect pointer info was omitted, likely due to not considering multi-device cases. This was not a problem with CPU-only platforms, but affects migration of indirect-access buffers residing on other devices' memories.
I have additional tests upcoming in a later PR.
> CPU: indirect SVM/USM was not set

- pocld/CMakeLists.txt
Compatibility with cmake versions <3.5 has been removed in cmake 4.0: https://cmake.org/cmake/help/latest/release/4.0.html#deprecated-and-removed-features
Without this patch, building with cmake 4.0 causes the following error message: 
```
CMake Error at pocld/CMakeLists.txt:27 (cmake_minimum_required):
Compatibility with CMake < 3.5 has been removed from CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```
> pocld: bump cmake minimum version to 3.5

- .github/workflows/build_julia.yml
This PR adds CI for Julia, running the OpenCL.jl test suite with PoCL as the only enabled platform (see https://juliagpu.org/post/2025-01-13-opencl_0.10/#jll-based_opencl_drivers for context). I opted to do a build that mimics our use of PoCL as closely as possible:
- using Julia's so-called JLLs to provide binary dependencies
- dynamically linking against the `libLLVM` that's provided by Julia itself (hence the `LD_LIBRARY_DIR` modification during compilation)
- register `libpocl` by overriding the one from the `pocl_jll` binary package, which also provides ~hacks~ wrapper scripts that allow PoCL to execute binaries like `clang` and `ldd`: https://github.com/JuliaPackaging/Yggdrasil/blob/01453664dd8489ef3b4ad6c50dddfa86402b013e/P/pocl/build_tarballs.jl#L161-L239 (this is why I opened an …
> Add Julia CI

- lib/CL/devices/level0/level0-driver.cc
On an Arrow Lake machine where there are multiple command queue groups to create queues from, picking the lowest ordinal speed up OpenVINO inference:
* `benchmark_app -d GPU.0 -hint none -nstreams 1 -nireq 1 -b 1 -t 20 -m resnet-50/resnet-50.xml`: 8 FPS -> 24 FPS.
* `benchmark_app -d GPU.0 -hint none -nstreams 2 -nireq 4 -b 1 -t 20 -m resnet-50/resnet-50.xml`: 28 FPS -> 40 FPS.
However, reportedly gains are not seen on Intel Battlemage GPUs.
> level0: pick smallest queue ordinals

- lib/CL/pocl_llvm_build.cc
721733862ad2 introduced a commit to not pass -cl-fast-relaxed-math directly to Clang as it caused to inaccurate divisions in some cases. However, the passed flags do not the introduce essential relaxation attribute 'reassoc' which is required for generating vectorized reduction trees from float reduction loops.
The rounding problems seem to be fixed starting LLVM 18, thus we can disable the workaround for newer LLVMs.
> The workaround for reduced fast flags not needed for LLVM 18+

- lib/CL/CMakeLists.txt
Without it, I run into the dreaded `export ordinal too large` error caused by too many symbols being exported (when statically linking LLVM):
```
FAILED: lib/CL/pocl.dll lib/CL/libpocl.dll.a
C:\WINDOWS\system32\cmd.exe /C "cd . && C:\msys64\mingw64\bin\c++.exe -fdiagnostics-color=always -O3 -DNDEBUG  -LC:/Users/Tim/Julia/src/llvm-project/install/dev/lib    -Wl,--enable-auto-import,--enable-runtime-pseudo-reloc -shared -o lib\CL\pocl.dll -Wl,--out-implib,lib\CL\libpocl.dll.a -Wl,--major-image-version,2,--minor-image-version,15 @CMakeFiles\pocl.rsp && cd ."
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/15.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: export ordinal too large: 90735
collect2.exe: error: ld returned 1 exit status    
```
> MinGW: Also use `--exclude-libs,ALL`

- lib/CL/pocl_cl.h
For a deployment situation I would like to both disable ICD support as well as renaming the POCL symbols.
I only want to access the pthread devices and want to avoid any symbol collisions with other OpenCL libraries
that may be loaded.
> Allow for -DENABLE_ICD=OFF -DRENAME_POCL=ON

- lib/kernel/subgroups.cl
Fixes incorrect behaviour: previous value was not used, but the current value wrapped instead.
> Fix a bug in intel_sub_group_shuffle_up

- examples/conformance/CMakeLists.txt
- include/CL/cl.h
- include/CL/cl_ext.h
- include/CL/cl_icd.h
- include/CL/opencl.h
- lib/CL/clGetPlatformIDs.c
This is mainly to add `cl_khr_spirv_queries` to list of recognized extensions, missing of which caused the weekly Full CTS runs to fail, but also fixes a few bugs found.
> Update OpenCL-CTS + OpenCL headers
