pocl/pocl

- README.Windows
- windows/setup_and_build_win64.sh
Removed vague build instructions and added script which can be run in `Git Bash` to download all deps and build llvm and then pocl. Added new directory for build script and windows dependent stuff as there is for android.
> Updated Windows readme with complete build script.

- examples/OpenCV/opencv.patch
Added opencv.patch for OpenCV 3.0.
> Added opencv.patch

- lib/CL/clFinish.c
- lib/CL/pocl_util.c
This fixes issue #171. I've also taken the opportunity to do some whitespace cleanup and typo comment fixes en passant.
> Always clone event list

- lib/CL/devices/cpuinfo.c
- lib/CL/devices/topology/pocl_topology.c
Try to fill CL_DEVICE_VENDOR and CL_DEVICE_VENDOR_ID with meaningful values (for appropriate definitions of «meaningful»).
> Device vendor

- CHANGES
- TODO
- examples/AMD/AMDSDK.patch
- examples/AMDSDK2.9/AMDSDK2_9.patch
- lib/CL/clBuildProgram.c
- lib/CL/clCreateKernelsInProgram.c
- lib/CL/clCreateProgramWithBinary.c
- lib/CL/clCreateProgramWithSource.c
- lib/CL/clCreateSubDevices.c
- lib/CL/clGetDeviceInfo.c
- lib/CL/clReleaseDevice.c
- lib/CL/clRetainDevice.c
- lib/CL/devices/basic/basic.c
- lib/CL/devices/cellspu/cellspu.c
- lib/CL/devices/pthread/pthread.c
- lib/CL/devices/tce/ttasim/ttasim.cc
- lib/CL/pocl_cl.h
- lib/CL/pocl_llvm.h
- lib/CL/pocl_llvm_api.cc
- lib/CL/pocl_util.h
- tests/runtime/CMakeLists.txt
- tests/runtime/Makefile.am
- tests/runtime/test_clCreateKernelsInProgram.c
- tests/runtime/test_clCreateSubDevices.c
- tests/testsuite-runtime.at
A test for and a draft implementation of clCreateSubDevices.
> Subdevices

- lib/CL/clFinish.c
Add minor missing check for command queue pointer.
> clFinish: add check for command_queue pointer to be non null

- lib/CL/clWaitForEvents.c
Add checks for event list and num_event.
> clWaitForEvents: add check for parameters

- doc/sphinx/source/env_variables.rst
- lib/CL/pocl_cache.c
Fixes #200. Also checked the return value from `snprintf` while I was at it.
> Use XDG_CACHE_HOME

- lib/kernel/vecmathlib-pocl/frexp.cl
- lib/kernel/vecmathlib-pocl/generate-files.py
- tests/testsuite.at
> Correct frexp implementation

- include/_kernel_c.h
- include/_kernel_constants.h
- lib/CL/clSetKernelArg.c
- lib/CL/devices/basic/basic.c
- lib/CL/devices/common.c
- lib/CL/devices/common.h
- lib/CL/devices/dev_image.h
- lib/CL/devices/pthread/pthread.c
Initialize the device specific `dev_sampler_t` structure from the `cl_sampler_t` structure for the basic and pthread devices.
> Initialize sampler argument

- include/CMakeLists.txt
- lib/CL/clGetDeviceIDs.c
- Contains fix to clGetDeviceIDs when no device of queried device type is found
- Contains fix to add missing file to cmake install command
> Minor fix to clGetDeviceIDs and cmake install

- doc/notes-0.12.txt
- lib/CL/Makefile.am
- lib/CL/devices/basic/basic.c
- lib/CL/devices/pthread/pthread.c
- lib/CL/devices/topology/pocl_topology.c
- tests/testsuite-tce.at
Hwloc OpenCL plugin hack and trying to thank HSA properly :)
> Release 0 12 fixes

- .mailmap
- lib/CL/clCreateCommandQueue.c
- lib/CL/clReleaseCommandQueue.c
- lib/CL/clReleaseMemObject.c
- lib/CL/clReleaseProgram.c
A couple of retain/release consistency fixes, plus a bonus mailmap
> Retain fixes

- include/_kernel.h
- lib/kernel/svm_atomics.cl
- lib/kernel/svm_atomics.h
- lib/kernel/svm_atomics_host.cl
- lib/llvmopencl/TargetAddressSpaces.cc
- tests/CMakeLists.txt
- tests/regression/CMakeLists.txt
- tests/runtime/CMakeLists.txt
* Fix finegrainsvmcas testcase with llvm 3.8
* Don't disable regression tests on cl.hpp conditional
* Add a few forgotten tests to CMake
* Handle generic AS on GEP (fixes constant array regression test)
> Few more fixes before branching

- lib/CL/clGetDeviceInfo.c
- lib/CL/devices/basic/basic.c
- lib/CL/devices/hsa/pocl-hsa.c
- lib/CL/pocl_cl.h
A couple of minor fixes for device properties about images.
> Device image info

- lib/CL/pocl_binary.c
Fails to build for me on OS X otherwise.
> Use alternative endian.h functions on OS X

- lib/CL/clCreateUserEvent.c
- lib/CL/clGetEventProfilingInfo.c
- lib/CL/clSetUserEventStatus.c
- lib/CL/pocl_mem_management.c
- tests/runtime/CMakeLists.txt
- tests/runtime/test_user_event.c
A collection of fixes for user event handling, including tests.
> User event fixes

- .mailmap
Just two minor fixes to the mailmap.
> Email fixes

- lib/CL/clBuildProgram.c
- lib/CL/clGetDeviceInfo.c
Fix some details according to the spec.
> OCS: fix error codes to match spec when disabling online compiler support

- lib/CL/devices/tce/tce_common.cc
Fix for tce devices ignoring offset parameter in buffer writes and reads.
> Fix tce buffer r/w operations

- CMakeLists.txt
- cmake/LLVM.cmake
- lib/CMakeLists.txt
Make pocl build on my computer again :)
> two build fixes

- lib/CL/pocl_llvm_api.cc
> Work around Skylake codegen issue in LLVM 3.8 (master)

- examples/Parboil/README
Parboil link in the README file updated
> Corrected Parboil link in README

- lib/CL/clCreateImage.c
Added Supported image format free into error condition as well
> clCreateImage add free into error condition

- lib/CL/devices/cuda/pocl-cuda.c
- lib/CL/devices/devices.c
This fixes #472 and additionally introduces the possibility to use (or at least access) all available devices.
> Probe for CUDA devices

- lib/CL/devices/cuda/pocl-cuda.c
This addresses a couple of @vkorhonen's comments in PR #479.
> [CUDA] Address some issues in async handling

- lib/CL/clReleaseProgram.c
This fixes a memory leak of binaries allocated in clCreateProgramWithBinary.
cc: @inducer
> clReleaseProgram: Also free pocl_binaries

- lib/CL/devices/cuda/pocl-cuda.c
Previously suggested by @vkorhonen.
This change provides a noticeable improvement for a benchmark that uses multiple command queues, and still has some heavy lifting to do on the CPU side.
> [CUDA] Use pthread_cond_wait in background threads

- lib/CL/devices/cuda/pocl-cuda.c
- lib/CL/devices/cuda/pocl-ptx-gen.cc
Use `llvm::CloneFunctionInto()` to retain function attributes when cloning functions.
Also contains a fix for an occasional deadlock on queue destruction that was introduced in my previous commit.
> [CUDA] Retain function attributes when cloning functions

- lib/CL/devices/cuda/pocl-ptx-gen.cc
> [CUDA] Fix libdevice filename for CUDA 9+

- lib/CL/devices/cuda/pocl-cuda.c
This series cleans up CUDA attribute retrieval, and fixes a couple of minor issues.
> CUDA attribute retrieval clean up and fixes

- CREDITS
This is for commit 3e20fc5db98ba7ba0ec5fed61cc61efe22e6b08c
> Added myself to CREDITS

- CHANGES
- lib/CL/devices/topology/pocl_topology.c
This is the same as PR #627 with added check for header-library incompatibility.
> Hwloc 2 support

- lib/CL/devices/cuda/pocl-ptx-gen.cc
> [CUDA] Map llvm.powi.* to __nv_powi*

- CMakeLists.txt
- lib/CL/pocl_llvm_build.cc
- lib/CL/pocl_llvm_metadata.cc
- lib/CL/pocl_llvm_utils.cc
- lib/CL/pocl_llvm_wg.cc
- lib/llvmopencl/CompilerWarnings.h
- lib/llvmopencl/RemoveBarrierCalls.h
- lib/llvmopencl/WorkItemAliasAnalysis.cc
- lib/llvmopencl/Workgroup.cc
- lib/llvmopencl/WorkitemLoops.cc
> LLVM 10 support

- cmake/LLVM.cmake
- config.h.in.cmake
- include/CMakeLists.txt
- include/_kernel.h
- include/_libclang_versions_checks.h
- include/pocl.h
- lib/CL/pocl_llvm_wg.cc
- lib/kernel/CMakeLists.txt
1. fixed the mess in macrodefs making adding support of new versions a nightmare
2. brought support to llvm and clang 11
> LLVM11 support

- lib/llvmopencl/HandleSamplerInitialization.cc
- lib/llvmopencl/HandleSamplerInitialization.h
- lib/llvmopencl/Workgroup.cc
- lib/llvmopencl/WorkitemLoops.cc
https://github.com/llvm/llvm-project/commit/4f04db4b5439f390c48408f9b94875810e88ffc6
https://github.com/llvm/llvm-project/commit/a58b62b4a2b96c31b49338b262b609db746449e8
https://github.com/llvm/llvm-project/commit/4aae4e3f48b9156755c4cfc7ad63fe2a7029d9d7
.
> Fixing llvm11 support due to recent changes:

- examples/AMDSDK3.0/amdsdk3_0.patch
- examples/CMakeLists.txt
- examples/conformance/CMakeLists.txt
- lib/CL/devices/cuda/pocl-ptx-gen.cc
- lib/CL/devices/tce/CMakeLists.txt
- lib/CL/devices/tce/tce_common.cc
- lib/CL/pocl_build.c
- lib/CL/pocl_llvm_build.cc
- lib/kernel/host/CMakeLists.txt
- tests/kernel/image_query_funcs.c
- tests/kernel/kernel.c
- tests/kernel/sampler_address_clamp.c
- tests/kernel/test_shuffle.cc
- tests/runtime/CMakeLists.txt
- tests/runtime/test_clGetSupportedImageFormats.c
- tests/runtime/test_fill-buffer.c
some fixes required for next pocl release
> next release (LLVM 11) fixes

- lib/llvmopencl/WorkitemLoops.cc
https://reviews.llvm.org/rG8e0148dff703dd1ff12cc143482274233a8dacf3
> Fix changes in getAllocationSizeInBits() return type

- lib/llvmopencl/IsolateRegions.cc
Remove some unnecessary code and variables which are not used. Most likely from copy paste or something else.
> Remove redundant code

- include/CL/cl_ext.h
Thanks to @Oblomov for pointing this out!
> fix DOMAIN_ID to the same value as used by the Nvidia CL driver

- cmake/LLVM.cmake
- include/_kernel.h
- lib/CL/pocl_llvm_build.cc
Add support for LLVM 13 main and 12 release branches.
> LLVM 13 support

- CMakeLists.txt
- ToolchainExample.cmake
- cmake/FindHwloc.cmake
- cmake/LLVM.cmake
- doc/sphinx/source/install.rst
I'm trying to cross compile for macos-arm64 from macos-x86_64.
> Support cross compiling pocl

- lib/CL/pocl_llvm_build.cc
Fixes https://github.com/pocl/pocl/issues/932
> Keep LLVM defaults for unroll, vectorize for SPMD devices

- CHANGES
- CREDITS
I was unsure on how the changes should be formatted since they haven't been released yet, so I took a guess based on the history of the file.
Requested in #948 #949 #950
> Add CREDITS and CHANGES entries for my changes.

- lib/kernel/cuda/atomic_add.ll
- lib/kernel/cuda/atomic_and.ll
- lib/kernel/cuda/atomic_cmpxchg.ll
- lib/kernel/cuda/atomic_dec.ll
- lib/kernel/cuda/atomic_inc.ll
- lib/kernel/cuda/atomic_max.ll
- lib/kernel/cuda/atomic_min.ll
- lib/kernel/cuda/atomic_or.ll
- lib/kernel/cuda/atomic_sub.ll
- lib/kernel/cuda/atomic_xchg.ll
- lib/kernel/cuda/atomic_xor.ll
Rename done in b3e616e2b81689755f7f310dc48191d3208317fb was incomplete
Fixes #955
> Fix cuda atomics after rename

- lib/CL/devices/devices.c
On linux, a user application can find a *.so with the
LD_LIBRARY_PATH evironment variable.
To use the LD_LIBRARY_PATH, the path returned by
get_pocl_device_lib_path() needs to be just the file name.
So add option to do this.
In pocl_init_device() if the current method fails, try again
with the fallback.
> Add a fallback to finding the device's *.so

- include/CL/CMakeLists.txt
> Add missing cl_ext_pocl.h to install.

- lib/CL/devices/cuda/pocl-cuda.c
Two trivial fixes for the CUDA device.
cc @jrprice
> CUDA cleanup

- CREDITS
- lib/CL/devices/cuda/pocl-ptx-gen.cc
- lib/llvmopencl/OptimizeWorkItemFuncCalls.cc
- lib/llvmopencl/ParallelRegion.cc
Fixes https://github.com/pocl/pocl/issues/990 to build with LLVM 14
> Fixing use or removed APIs

- CHANGES
- lib/CL/pocl_build.c
- lib/CL/pocl_llvm_build.cc
- lib/CL/pocl_util.c
- lib/CL/pocl_util.h
- tests/runtime/test_dlopen.c
details in issue #962 
at the moment I only tried it outside POCL
> handling whitespace chars in build options

- lib/CL/devices/cuda/pocl-ptx-gen.cc
- lib/kernel/cuda/CMakeLists.txt
- lib/kernel/cuda/rsqrt.cl
> Use __nv_rsqrt for rsqrt

- cmake/LLVM.cmake
- include/_kernel.h
- include/_libclang_versions_checks.h
Clang 15 has been released.  This is first step to supporting it.
> Add clang-15 build infra

- CMakeLists.txt
- config.h.in.cmake
- lib/llvmopencl/LLVMUtils.h
- lib/llvmopencl/Workgroup.cc
- lib/llvmopencl/WorkitemLoops.cc
- lib/llvmopencl/linker.cpp
Copied  #1086 with the additional commit fixing the BuildGEP2-calls in Workgroup.cc
> llvm14 opaque ptr with the additional buildgep2-fix

- README.PPC64le
- README.md
> Some documentation on the build on IBM power9

- .github/workflows/build_cmake.yml
- .github/workflows/full_cts.yml
- cmake/add_test_pocl.cmake
> expand test matrix with new runners

- lib/kernel/subgroups.c
These were revealed by rocprim/test_warp_reduce.
The main questions in my mind are
1) How could the CTS for ballot pass when I "implemented this"? 2) How can a sober man produce so many bugs to such a sort function?
> Multiple fixes to sub_group_ballot()

- .github/workflows/build_cmake.yml
- doc/sphinx/source/remote.rst
- doc/www/remote-backend.mak
- include/messages.h
- include/pocl.h
- lib/CL/clEnqueueCommandBufferKHR.c
- lib/CL/devices/common_driver.c
- lib/CL/devices/remote/communication.c
- lib/CL/devices/remote/communication.h
- lib/CL/devices/remote/remote.c
- lib/CL/pocl_mem_management.h
- lib/CL/pocl_util.c
- pocld/cmd_queue.cc
- pocld/reply_th.cc
- pocld/shared_cl_context.cc
- pocld/shared_cl_context.hh
- pocld/virtual_cl_context.cc
- tests/runtime/CMakeLists.txt
- tests/runtime/test_cl_pocl_content_size_migration.c
- tools/scripts/test_remote_runner_multi.sh
- tools/scripts/test_remote_runner_single.sh
- tools/scripts/test_remote_runner_with_local.sh
This was left out from the initial remote driver PR.
+ a couple of small tweaks
> remote: add basic cl_pocl_content_size support

- lib/CL/pocl_util.c
This avoids wonky behaviour if a command depends on size buffers but not their content buffer, such as `clEnqueueReadBuffer(..., size_buffer, ...)`.
> migrate: keep an explicit list of migrated buffers between the size and content steps

- lib/CL/clGetProgramBuildInfo.c
- lib/CL/clGetProgramInfo.c
> A couple of small conformance fixes to program queries

- examples/CMakeLists.txt
- examples/measure_overhead/CMakeLists.txt
- examples/measure_overhead/measure_distributed_matmul.cc
- examples/measure_overhead/measure_migration_overhead.cc
- examples/measure_overhead/measure_round_trip_overhead.cc
- lib/kernel/cuda/atomic_xchg_20.ll
- pocld/peer.cc
- pocld/rdma.cc
- pocld/rdma.hh
- pocld/rdma_reply_th.cc
Mainly improvements to the overhead measurement benchmarks, one bugfix for RDMA and one for CUDA.
> Miscellaneous fixes

- lib/CL/clCreateSubDevices.c
- lib/CL/clReleaseDevice.c
Unless I am mistaken, this should fix https://github.com/pocl/pocl/issues/1356
> Retain and release parent device when creating and releasing sub-devices

- lib/CL/clGetGLContextInfoKHR.c
- lib/CL/devices/devices.c
- lib/CL/pocl_cl.h
Changes to support the solutions in #1389.
> converted pocl_devices from array to linked list

- include/CL/cl_ext_pocl.h
- pocld/rdma.cc
- tests/runtime/test_pinned_buffers.cpp
- tests/runtime/test_svm.cpp
The most trivial changes from #1381
> Small fixes

- pocld/daemon.cc
Should reduce debugging time a lot if indexing several independent arrays ever goes awry again.
> pocld: add some bounds checking in PoclDaemon

- pocld/shared_cl_context.cc
> Fix ENABLE_LLVM=0 build

- pocld/daemon.cc
- pocld/rdma_reply_th.cc
- pocld/reply_th.cc
This should fix the recent RDMA CI issues.
> pocld: zero-initialize Requests harder

- lib/CL/devices/remote/remote.c
- pocld/shared_cl_context.cc
Instead of a single maximum allocation, try to allocate as many times as clSVMAlloc() returns a nullptr. 
The allocated regions might have gaps for which there is a maximum threshold, depending on the luck we have with the driver's memory allocator. At least for my Intel iGPU this allows to SVM-allocate most of the global memory.
In the host-side the region must be allocated as a continuous area from the minimum to the maximum allocated address (including the unallocatable gaps).
Starting point for USM support in PoCL-R is not yet finished. It simply allocates a CG SVM always, which works for device allocations. The host USM is not client-mapped by default like it should (IIUC), for example.
> PoCL-R: multiple svm regions to maximize the SVM allocation capabilities + starting point for USM support

- lib/CL/devices/remote/communication.c
- lib/CL/devices/remote/remote.c
Two small fixes to run the master pocl branch on android. See the extra messages in the git commit for details why.
> Android fixes

- lib/CL/clMemAllocINTEL.c
- lib/CL/clSVMAlloc.c
- lib/CL/clSetKernelExecInfo.c
- lib/CL/devices/basic/basic.c
- lib/CL/devices/level0/pocl-level0.cc
- lib/CL/devices/remote/remote.c
- lib/CL/pocl_build.c
- lib/CL/pocl_cl.h
- lib/CL/pocl_llvm_build.cc
- lib/CL/pocl_util.c
Please check the commits list.
> Some fixes

- doc/sphinx/source/notes_6_0.rst
- lib/CL/devices/level0/level0-compilation.cc
- lib/CL/devices/level0/level0-driver.cc
- lib/CL/devices/level0/level0-driver.hh
- lib/CL/devices/level0/pocl-level0.cc
- lib/CL/pocl_util.c
- tests/runtime/CMakeLists.txt
- tests/runtime/test_large_buf.cpp
- tests/spirv/CMakeLists.txt
Some bug fixes & performance optimizations (command batching)
> Level Zero improvements

- lib/CL/devices/cuda/pocl-cuda.c
- lib/CL/devices/cuda/pocl-ptx-gen.cc
- lib/CL/pocl_build.c
- tests/runtime/CMakeLists.txt
- tests/runtime/test_compile_n_link.cpp
More details in the commit logs.
Resolves #1474.
> CUDA: Fix separate compilation and link of programs

- lib/CL/devices/cuda/pocl-cuda.c
- tests/runtime/CMakeLists.txt
Also, enable test_svm for cuda.
Resolves #1465.
> CUDA: Fix clSVMAlloc()

- doc/sphinx/source/notes_6_0.rst
- lib/CL/devices/level0/level0-driver.cc
- lib/CL/pocl_util.c
- tests/runtime/CMakeLists.txt
- tests/runtime/test_subbuffers.cpp
It didn't add the offset of the sub-buffers when calling the kernel.
Fixes the conformance test and the new subbuffer test I add with this PR.
> L0 sub-buffers fix

- lib/CL/devices/level0/level0-compilation.cc
- lib/CL/devices/level0/level0-driver.cc
- lib/CL/devices/level0/level0-driver.hh
- lib/CL/devices/level0/pocl-level0.cc
- lib/CL/pocl_fill_memobj.c
- tests/kernel/CMakeLists.txt
* fix argument order of getImagefillKernel
* fix SHA1 calculation of memfill/imagefill kernels
this makes tests/kernel/test_image_query_funcs pass.
> Level Zero: fix images

- lib/kernel/subgroups.cl
Fixed a bug in previous shuffle_down (uint) implementation and extended/added implementations for all scalar types.
Gromacs OpenCL backend has option to utilize these shuffles.
> Implement missing intel_sub_group_shuffle_down/up for scalar types

- doc/sphinx/source/using.rst
- lib/CL/devices/level0/level0-driver.cc
- lib/CL/devices/level0/pocl-level0.cc
two performance fixes, one debugging / optimization aid
> Level Zero fixes

- lib/CL/pocl_lttng.h
- lib/CL/pocl_tracing.c
- tools/scripts/babel_parse.py
This pr adds tracing of migrations. This is already done in text tracing
> lttng: add migration tracepoint

- CMakeLists.txt
- config.h.in.cmake
- include/CL/cl_ext_pocl.h
- lib/CL/devices/remote/communication.c
- lib/CL/devices/remote/communication.h
- lib/CL/devices/remote/remote.c
- pocld/pocld.cc
some message related additions as part of the upstreaming process
> Poclr messages

- lib/CL/pocl_llvm_wg.cc
- lib/llvmopencl/ImplicitConditionalBarriers.cc
- lib/llvmopencl/IsolateRegions.cc
- lib/llvmopencl/LoopBarriers.cc
- tests/regression/test_alignment_with_dynamic_wg.cpp
- tests/workgroup/CMakeLists.txt
Pushing misc. loopvec improvements in smaller chunks.
> Misc loopvec improvements

- doc/sphinx/source/development.rst
Summation of previous discussions regarding documentation.
> doc: add entry about documenting guidelines

- CMakeLists.txt
- config.h.in.cmake
- lib/CL/CMakeLists.txt
- lib/CL/clCreateProgramWithIL.c
- lib/CL/devices/common.c
- lib/CL/devices/common_driver.c
- lib/CL/devices/devices.c
- lib/CL/devices/proxy/libopencl_stub/libopencl.c
- lib/CL/pocl_dynlib.c
- lib/CL/pocl_dynlib.h
- lib/CL/pocl_llvm_dynlib.cc
This helps portability to non-POSIX platforms.
> Allow using LLVM Support lib for dynlibs

- lib/CL/clGetDeviceInfo.c
- lib/CL/devices/remote/communication.c
- lib/CL/devices/remote/communication.h
- lib/CL/devices/remote/remote.h
- lib/CL/pocl_networking.h
- lib/CL/pocl_threads.h
- lib/CL/pocl_threads_c.h
- pocld/daemon.cc
- pocld/daemon.hh
- pocld/reply_th.cc
- pocld/virtual_cl_context.cc
- tests/runtime/test_buffer_ping_pong.c
> remote: Rework reconnection code

- lib/CL/devices/printf_buffer.c
also includes fixing uint to int conversion
warning and some other clang tidy warnings.
> misc: fix dangling pointer in printf_buffer

- lib/CL/pocl_binary.c
- lib/CL/pocl_file_util.c
- lib/CL/pocl_file_util.h
- lib/CL/pocl_llvm_file_utils.cc
- tests/CMakeLists.txt
- tests/unit/CMakeLists.txt
- tests/unit/input/somedir/oops.txt
- tests/unit/input/somefile.txt
- tests/unit/test_fs.cc
Also, add new test subdirectory for unit testing starting with tests on the new utils.
> New file utils, adjust pocl_binary.c for MSVC

- .github/workflows/build_msvc.yml
- tools/scripts/run_cpu_tests.ps1
All [new tests](https://github.com/linehill/pocl/actions/runs/11795339269) should be passing.
> Add GitHub hosted CI for MSVC toolchain.

- .github/workflows/build_full_cts.yml
- .github/workflows/build_mingw.yml
- .github/workflows/build_msvc.yml
- .github/workflows/build_only.yml
- cmake/LLVM.cmake
- examples/UnitCL/CMakeLists.txt
- tools/docker/OpenCL-CTS/run_full_cts.dockerfile
Adds a Dockerfile to build & run the full OpenCL CTS using official runner script.
> CTS / GH workflow fixes

- .github/workflows/build_level0.yml
Needs to be investigated; these broke after moving the GPU CI.
> Disable some Level0 tests temporarily.

- lib/CL/devices/CMakeLists.txt
- lib/CL/devices/common_utils.c
- lib/CL/devices/common_utils.h
- lib/CL/devices/cpu_dbk/CMakeLists.txt
- lib/CL/devices/cpu_dbk/pocl_dbk_khr_dnn_utils.cpp
- lib/CL/devices/cpu_dbk/pocl_dbk_khr_img_cpu.c
- lib/CL/devices/cpu_dbk/pocl_dbk_khr_jpeg_cpu.c
- lib/CL/pocl_mem_management.c
- lib/CL/pocl_mem_management.h
I noticed a circular dependency that would occasionally cause problems.
> dbk: fix circular dependency

- examples/accel/OpenCLcontext.cpp
- examples/accel/OpenCLcontext.h
- lib/CL/devices/cuda/pocl-cuda.c
- lib/CL/devices/cuda/pocl-ptx-gen.cc
- lib/CL/pocl_llvm_wg.cc
- tests/regression/test_issue_1525.cpp
Things fixed:
* accel: couple of header changes
* cuda: unused function and sign compares
* llvm-wg: braces in assert
* test: removal of target ocl version
> misc: fix build warnings

- lib/CL/devices/pthread/pthread_scheduler.c
This was left over after #1627
> pthread: remove extra argument in function call

- doc/sphinx/source/notes_6_1.rst
Closes https://github.com/pocl/pocl/issues/1766
@pjaaskel Let me know if you want more/less details.
> Add description of Julia integration to 6.1 release. notes

- lib/llvmopencl/linker.cpp
These seem to have bit-rotted over time.
> Fix some DB_PRINT statements in linker

- doc/sphinx/source/sycl_dpcpp.rst
- doc/sphinx/source/using.rst
Addresses #1801
- Added DPC++ documentation.
- Fixed reference to POCL_DRIVER_VERSION_OVERRIDE.
> Add documentation for how to setup and use DPC++ with PoCL

- doc/sphinx/source/notes_7_0.rst
> update release notes

- lib/llvmopencl/WorkitemLoops.cc
Sometimes when rematerializing an alloca, the initializer could fail to remat and we detected that too late. Now detects remat-ability early to ensure the rematerialization can be successful.
Also removed the Phi branch as we should not encounter them at this point any longer.
I have tests that trigger without this in the private branch which will be upstreamed Soon.
> Remat: Robustness for AllocaInst handling

- lib/CL/devices/cuda/pocl-cuda.c
https://github.com/pocl/pocl/issues/1885
> Fix memory leak when creating/destroying queues with CUDA backend

- doc/sphinx/source/remote.rst
> doc: update remote docs
